"""Constants for DingTalk QR account binding."""

from __future__ import annotations

BIND_TOKEN_TTL_SECONDS = 600
BIND_TOKEN_KEY_PREFIX = "dingtalk_bind:"
BIND_MINTER_PREFIX = "dingtalk_bind:minter:"
BIND_PATH_MARKER = "/bind/dingtalk"
BIND_QUERY_PARAM = "t"
BIND_QUERY_CODE_PARAM = "c"
BIND_CODE_SECRET_FIELD = "bind_code_secret"
BIND_CONSUMED_PREFIX = "dingtalk_bind:consumed:"

BIND_ERROR_TOKEN_EXPIRED = "MINDBOT_BIND_TOKEN_EXPIRED"
BIND_ERROR_TOKEN_CONSUMED = "MINDBOT_BIND_TOKEN_CONSUMED"
BIND_ERROR_ORG_MISMATCH = "MINDBOT_BIND_ORG_MISMATCH"
BIND_ERROR_INTERNAL = "MINDBOT_BIND_INTERNAL"
BIND_ERROR_STAFF_TAKEN = "MINDBOT_BIND_STAFF_TAKEN"
