from typing import Any, Callable

class User: ...

def between(min_wait: float, max_wait: float) -> Callable[..., Any]: ...
def tag(*tags: str) -> Callable[..., Any]: ...
def task(*args: Any, **kwargs: Any) -> Callable[..., Any]: ...

class events:
    @staticmethod
    def init(listener: Callable[..., Any]) -> None: ...
