"""CosyVoice v2 system voices (Aliyun Model Studio).

Copyright 2024-2025 北京思源智教科技有限公司 (Beijing Siyuan Zhijiao Technology Co., Ltd.)
All Rights Reserved
Proprietary License
"""

from __future__ import annotations

from services.tts.voices.types import (
    BJ,
    COSY_V2,
    FAMILY_COSYVOICE,
    ZH_DONGBEI_EN,
    ZH_EN,
    ZH_MIN_EN,
    ZH_SHAANXI_EN,
    ZH_YUE_EN,
    TtsVoice,
    make_voice,
)

_V2 = (COSY_V2,)


def _cv(
    voice_id: str,
    name: str,
    scene: str,
    trait: str,
    languages: tuple[str, ...] = ZH_EN,
) -> TtsVoice:
    """CosyVoice v2 Chinese / dialect system voice."""
    return make_voice(
        voice_id,
        name,
        scene,
        trait,
        languages,
        family=FAMILY_COSYVOICE,
        models=_V2,
        ssml=True,
        word_timestamp=True,
        regions=BJ,
    )


def _en(
    voice_id: str,
    name: str,
    trait: str,
    language: str,
    *,
    ssml: bool = False,
) -> TtsVoice:
    """CosyVoice v2 overseas voice (timestamp unsupported)."""
    return make_voice(
        voice_id,
        name,
        "出海营销",
        trait,
        (language,),
        family=FAMILY_COSYVOICE,
        models=_V2,
        ssml=ssml,
        regions=BJ,
    )


COSYVOICE_V2_VOICES: tuple[TtsVoice, ...] = (
    _cv("longyingxiao", "龙应笑", "电话销售", "清甜推销女"),
    _cv("longjiqi", "龙机器", "短视频配音", "呆萌机器人"),
    _cv("longhouge", "龙猴哥", "短视频配音", "经典猴哥"),
    _cv("longjixin", "龙机心", "短视频配音", "毒舌心机女"),
    _cv("longanyue", "龙安粤", "短视频配音", "欢脱粤语男", ZH_YUE_EN),
    _cv("longshange", "龙陕哥", "短视频配音", "原味陕北男", ZH_SHAANXI_EN),
    _cv("longanmin", "龙安敏", "短视频配音", "甜美闽南女", ZH_MIN_EN),
    _cv("longdaiyu", "龙黛玉", "短视频配音", "娇率才女音"),
    _cv("longgaoseng", "龙高僧", "短视频配音", "得道高僧音"),
    _cv("longanli", "龙安莉", "语音助手", "利落从容女"),
    _cv("longanlang", "龙安朗", "语音助手", "清爽利落男"),
    _cv("longanwen", "龙安温", "语音助手", "优雅知性女"),
    _cv("longanyun", "龙安昀", "语音助手", "居家暖男"),
    _cv("longyumi_v2", "YUMI", "语音助手", "正经青年女"),
    _cv("longxiaochun_v2", "龙小淳", "语音助手", "知性积极女"),
    _cv("longxiaoxia_v2", "龙小夏", "语音助手", "沉稳权威女"),
    _cv("longyichen", "龙逸尘", "有声书", "洒脱活力男"),
    _cv("longwanjun", "龙婉君", "有声书", "细腻柔声女"),
    _cv("longlaobo", "龙老伯", "有声书", "沧桑岁月爷"),
    _cv("longlaoyi", "龙老姨", "有声书", "烟火从容阿姨"),
    _cv("longbaizhi", "龙白芷", "有声书", "睿气旁白女"),
    _cv("longsanshu", "龙三叔", "有声书", "沉稳质感男"),
    _cv("longxiu_v2", "龙修", "有声书", "博才说书男"),
    _cv("longmiao_v2", "龙妙", "有声书", "抑扬顿挫女"),
    _cv("longyue_v2", "龙悦", "有声书", "温暖磁性女"),
    _cv("longnan_v2", "龙楠", "有声书", "睿智青年男"),
    _cv("longyuan_v2", "龙媛", "有声书", "温暖治愈女"),
    _cv("longanqin", "龙安亲", "社交陪伴", "亲和活泼女"),
    _cv("longanya", "龙安雅", "社交陪伴", "高雅气质女"),
    _cv("longanshuo", "龙安朔", "社交陪伴", "干净清爽男"),
    _cv("longanling", "龙安灵", "社交陪伴", "思维灵动女"),
    _cv("longanzhi", "龙安智", "社交陪伴", "睿智轻熟男"),
    _cv("longanrou", "龙安柔", "社交陪伴", "温柔闺蜜女"),
    _cv("longqiang_v2", "龙嫱", "社交陪伴", "浪漫风情女"),
    _cv("longhan_v2", "龙寒", "社交陪伴", "温暖痴情男"),
    _cv("longxing_v2", "龙星", "社交陪伴", "温婉邻家女"),
    _cv("longhua_v2", "龙华", "社交陪伴", "元气甜美女"),
    _cv("longwan_v2", "龙婉", "社交陪伴", "积极知性女"),
    _cv("longcheng_v2", "龙橙", "社交陪伴", "智慧青年男"),
    _cv("longfeifei_v2", "龙菲菲", "社交陪伴", "甜美娇气女"),
    _cv("longxiaocheng_v2", "龙小诚", "社交陪伴", "磁性低音男"),
    _cv("longzhe_v2", "龙哲", "社交陪伴", "呆板大暖男"),
    _cv("longyan_v2", "龙颜", "社交陪伴", "温暖春风女"),
    _cv("longtian_v2", "龙天", "社交陪伴", "磁性理智男"),
    _cv("longze_v2", "龙泽", "社交陪伴", "温暖元气男"),
    _cv("longshao_v2", "龙邵", "社交陪伴", "积极向上男"),
    _cv("longhao_v2", "龙浩", "社交陪伴", "多情忧郁男"),
    _cv("kabuleshen_v2", "龙深", "社交陪伴", "实力歌手男"),
    _cv("longhuhu", "龙呼呼", "童声", "天真烂漫女童"),
    _cv("longanpei", "龙安培", "教育培训", "青少年教师女"),
    _cv("longwangwang", "龙汪汪", "儿童陪伴", "台湾少年音"),
    _cv("longpaopao", "龙泡泡", "儿童陪伴", "飞天泡泡音"),
    _cv("longshanshan", "龙闪闪", "儿童有声书", "戏剧化童声"),
    _cv("longniuniu", "龙牛牛", "儿童有声书", "阳光男童声"),
    _cv("longyingmu", "龙应沐", "客服", "优雅知性女"),
    _cv("longyingxun", "龙应询", "客服", "年轻青涩男"),
    _cv("longyingcui", "龙应催", "客服", "严肃催收男"),
    _cv("longyingda", "龙应答", "客服", "开朗高音女"),
    _cv("longyingjing", "龙应静", "客服", "低调冷静女"),
    _cv("longyingyan", "龙应严", "客服", "义正严辞女"),
    _cv("longyingtian", "龙应甜", "客服", "温柔甜美女"),
    _cv("longyingbing", "龙应冰", "客服", "尖锐强势女"),
    _cv("longyingtao", "龙应桃", "客服", "温柔淡定女"),
    _cv("longyingling", "龙应聆", "客服", "温和共情女"),
    _cv("longanran", "龙安燃", "直播带货", "活泼质感女"),
    _cv("longanxuan", "龙安宣", "直播带货", "经典直播女"),
    _cv("longanchong", "龙安冲", "直播带货", "激情推销男"),
    _cv("longanping", "龙安萍", "直播带货", "高亢直播女"),
    _cv("longjielidou_v2", "龙杰力豆", "童声", "阳光顽皮男"),
    _cv("longling_v2", "龙铃", "童声", "稚气呆板女"),
    _cv("longke_v2", "龙可", "童声", "懵懂乖乖女"),
    _cv("longxian_v2", "龙仙", "童声", "豪放可爱女"),
    _cv("longlaotie_v2", "龙老铁", "方言", "东北直率男", ZH_DONGBEI_EN),
    _cv("longjiayi_v2", "龙嘉怡", "方言", "知性粤语女", ZH_YUE_EN),
    _cv("longtao_v2", "龙桃", "方言", "积极粤语女", ZH_YUE_EN),
    _cv("longfei_v2", "龙飞", "诗词朗诵", "热血磁性男"),
    _cv("libai_v2", "李白", "诗词朗诵", "古代诗仙男"),
    _cv("longjin_v2", "龙津", "诗词朗诵", "优雅温润男"),
    _cv("longshu_v2", "龙书", "新闻播报", "沉稳青年男"),
    _cv("loongbella_v2", "Bella2.0", "新闻播报", "精准干练女"),
    _cv("longshuo_v2", "龙硕", "新闻播报", "博才干练男"),
    _cv("longxiaobai_v2", "龙小白", "新闻播报", "沉稳播报女"),
    _cv("longjing_v2", "龙婧", "新闻播报", "典型播音女"),
    _cv("loongstella_v2", "loongstella", "新闻播报", "飒爽利落女"),
    _en("loongyuuna_v2", "loongyuuna", "元气霓虹女", "ja", ssml=True),
    _en("loongyuuma_v2", "loongyuuma", "干练霓虹男", "ja", ssml=True),
    _en("loongjihun_v2", "loongjihun", "阳光韩国男", "ko", ssml=True),
    _en("loongeva_v2", "loongeva", "知性英文女", "en-gb"),
    _en("loongbrian_v2", "loongbrian", "沉稳英文男", "en-gb"),
    _en("loongluna_v2", "loongluna", "英式英文女", "en-gb"),
    _en("loongluca_v2", "loongluca", "英式英文男", "en-gb"),
    _en("loongemily_v2", "loongemily", "英式英文女", "en-gb"),
    _en("loongeric_v2", "loongeric", "英式英文男", "en-gb"),
    _en("loongabby_v2", "loongabby", "美式英文女", "en-us"),
    _en("loongannie_v2", "loongannie", "美式英文女", "en-us"),
    _en("loongandy_v2", "loongandy", "美式英文男", "en-us"),
    _en("loongava_v2", "loongava", "美式英文女", "en-us"),
    _en("loongbeth_v2", "loongbeth", "美式英文女", "en-us"),
    _en("loongbetty_v2", "loongbetty", "美式英文女", "en-us"),
    _en("loongcindy_v2", "loongcindy", "美式英文女", "en-us"),
    _en("loongcally_v2", "loongcally", "美式英文女", "en-us"),
    _en("loongdavid_v2", "loongdavid", "美式英文男", "en-us"),
    _en("loongdonna_v2", "loongdonna", "美式英文女", "en-us"),
    _en("loongkyong_v2", "loongkyong", "韩语女", "ko"),
    _en("loongtomoka_v2", "loongtomoka", "日语女", "ja"),
    _en("loongtomoya_v2", "loongtomoya", "日语男", "ja"),
)
