"""WeCom 消息推送 (webhook) constants — doc 99110 / legacy 91770."""

from __future__ import annotations

WECOM_API_HOST = "qyapi.weixin.qq.com"
WECOM_WEBHOOK_SEND_PATH = "/cgi-bin/webhook/send"
WECOM_WEBHOOK_UPLOAD_MEDIA_PATH = "/cgi-bin/webhook/upload_media"

WEBHOOK_TEXT_MAX_BYTES = 2048
WEBHOOK_MARKDOWN_MAX_BYTES = 4096
WEBHOOK_MARKDOWN_V2_MAX_BYTES = 4096
WEBHOOK_NEWS_TITLE_MAX_BYTES = 128
WEBHOOK_NEWS_DESCRIPTION_MAX_BYTES = 512
WEBHOOK_NEWS_ARTICLES_MIN = 1
WEBHOOK_NEWS_ARTICLES_MAX = 8
WEBHOOK_IMAGE_MAX_BYTES = 2 * 1024 * 1024
WEBHOOK_FILE_MAX_BYTES = 20 * 1024 * 1024
WEBHOOK_VOICE_MAX_BYTES = 2 * 1024 * 1024
WEBHOOK_MESSAGES_PER_MINUTE = 20

DOC_WEBHOOK_CONFIG = "99110"
