"""Emit sq, ar, hi canvas.ts using nl line breaks and EN phrase-mapped values."""

from __future__ import annotations

import re
from collections.abc import Callable
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EN_PATH = ROOT / "src/locales/messages/en/canvas.ts"
NL_PATH = ROOT / "src/locales/messages/nl/canvas.ts"
LOCALES = {
    "sq": ROOT / "src/locales/messages/sq/canvas.ts",
    "ar": ROOT / "src/locales/messages/ar/canvas.ts",
    "hi": ROOT / "src/locales/messages/hi/canvas.ts",
}


def decode_ts_string(raw_inner: str) -> str:
    out: list[str] = []
    idx = 0
    while idx < len(raw_inner):
        if raw_inner[idx] == "\\" and idx + 1 < len(raw_inner):
            nxt = raw_inner[idx + 1]
            if nxt == "'":
                out.append("'")
                idx += 2
            elif nxt == "\\":
                out.append("\\")
                idx += 2
            else:
                out.append(raw_inner[idx])
                idx += 1
        else:
            out.append(raw_inner[idx])
            idx += 1
    return "".join(out)


def parse_values_ordered(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    body = text.split("export default {", 1)[1].rsplit("}", 1)[0]
    lines = body.splitlines()
    values: list[str] = []
    idx = 0
    while idx < len(lines):
        match = re.match(r"^\s*'([^']+)':\s*(.*)$", lines[idx].rstrip())
        if not match:
            idx += 1
            continue
        rest = match.group(2).strip()
        if rest == "":
            idx += 1
            val_line = lines[idx].strip()
            if val_line.endswith(","):
                val_line = val_line[:-1].strip()
            assert val_line.startswith("'") and val_line.endswith("'")
            values.append(decode_ts_string(val_line[1:-1]))
            idx += 1
        else:
            raw = rest
            if raw.endswith(","):
                raw = raw[:-1].strip()
            assert raw.startswith("'") and raw.endswith("'")
            values.append(decode_ts_string(raw[1:-1]))
            idx += 1
    return values


def nl_key_multiline_rows(text: str) -> list[tuple[str, bool]]:
    body = text.split("export default {", 1)[1].rsplit("}", 1)[0]
    lines = body.splitlines()
    rows: list[tuple[str, bool]] = []
    idx = 0
    while idx < len(lines):
        match = re.match(r"^(\s*)'([^']+)':\s*(.*)$", lines[idx].rstrip())
        if not match:
            idx += 1
            continue
        key, rest = match.group(2), match.group(3).strip()
        if rest == "":
            rows.append((key, True))
            idx += 2
        else:
            rows.append((key, False))
            idx += 1
    return rows


def encode_ts_single_quoted(value: str) -> str:
    parts: list[str] = []
    for char in value:
        if char == "\\":
            parts.append("\\\\")
        elif char == "'":
            parts.append("\\'")
        else:
            parts.append(char)
    return "".join(parts)


def apply_pairs(value: str, pairs: list[tuple[str, str]]) -> str:
    out = value
    for src, tgt in sorted(pairs, key=lambda x: -len(x[0])):
        out = out.replace(src, tgt)
    return out


def to_albanian(value: str) -> str:
    pairs: list[tuple[str, str]] = [
        ("Hello {username}, I'm your AI visual thinking assistant",
         "Përshëndetje {username}, unë jam asistenti yt i mendimit pamor me IA"),
        ("Enter the invitation code (xxx-xxx) to join their session.",
         "Shkruaj kodin e ftesës (xxx-xxx) për t’u bashkuar me sesionin e tyre."),
        ("No school sessions right now. A colleague must start “School collaboration” on the canvas.",
         "Nuk ka sesione shkollore aktive. Një koleg duhet të nisë «bashkëpunimin shkollor» në kanavacë."),
        ("Network error, failed to join", "Gabim rrjeti, bashkimi dështoi"),
        ("Could not load school sessions", "Nuk u ngarkuan dot sesionet shkollore"),
        ("Failed to join presentation", "Nuk u arrit të bashkohesh me prezantimin"),
        ("Failed to join", "Bashkimi dështoi"),
        ("Describe your diagram, or choose a template below...",
         "Përshkruaj diagramin ose zgjidh një shabllon më poshtë..."),
        ("Describe your diagram, or choose a template below…",
         "Përshkruaj diagramin ose zgjidh një shabllon më poshtë…"),
        ("Please enter the complete presentation code",
         "Shkruaj kodin e plotë të prezantimit"),
        ("Invalid presentation code format (should be xxx-xxx)",
         "Format i pavlefshëm i kodit të prezantimit (duhet xxx-xxx)"),
        ("Create on canvas", "Krijo në kanavacë"),
        ("Classify & group", "Klasifiko dhe grupo"),
        ("Cause & effect", "Shkak dhe pasojë"),
        ("Organize ideas", "Organizo idetë"),
        ("Sequence & steps", "Sekuencë dhe hapa"),
        ("Compare & contrast", "Krahaso dhe kundërvë"),
        ("Concept relations", "Marrëdhëniet e koncepteve"),
        ("Brainstorm & associate", "Stuhi ide dhe përshoqëro"),
        ("Describe attributes", "Përshkruaj atributet"),
        ("Analogies", "Analogji"),
        ("Whole & parts", "E tërëshme dhe pjesë"),
        ("Tree Map", "Harta e pemës"),
        ("Multi-Flow Map", "Harta me shumë rrjedhje"),
        ("Mind Map", "Harta mendore"),
        ("Flow Map", "Harta e rrjedhës"),
        ("Double Bubble Map", "Harta me dy flluska"),
        ("Concept Map", "Harta konceptuale"),
        ("Circle Map", "Harta rrethore"),
        ("Bubble Map", "Harta me flluska"),
        ("Bridge Map", "Harta urë"),
        ("Brace Map", "Harta me kllapa"),
        ("Choose a diagram type", "Zgjidh një lloj diagrami"),
        ("Space full, auto-save not available at the moment. Please delete existing diagrams to free more space.",
         "Hapësira është plot; ruajtja automatike nuk ofrohet për tani. Fshi diagramet ekzistuese për të liruar vend."),
        ("Select Diagram Type", "Zgjidh llojin e diagramit"),
        ("New Diagram", "Diagram i ri"),
        ("Fit to Screen", "Përshtat në ekran"),
        ("Export Image", "Eksporto imazhin"),
        ("Please log in to save", "Hyr për të ruajtur"),
        ("Saved {n}min ago", "U ruajt para {n} min"),
        ("Saved {n}s ago", "U ruajt para {n} s"),
        ("Saved just now", "U ruajt sapo"),
        ("Saved at {time}", "U ruajt në {time}"),
        ("Enter relationship...", "Shkruaj marrëdhënien..."),
        ("Press 1–5 to select", "Shtyp 1–5 për të zgjedhur"),
        ("click to specify...", "kliko për të specifikuar..."),
        ("[Click to set]", "[Kliko për të caktuar]"),
        ("Focus question: ", "Pyetja e fokusit: "),
        ("[Alternatives will appear here]", "[Alternativat do të shfaqen këtu]"),
        ("AI...", "IA..."),
        ("Validation request failed", "Kërkesa e vlerësimit dështoi"),
        ("No result", "Nuk ka rezultat"),
        ("Hand tool", "Mjeti dorë"),
        ("Click to restore snapshot {n} · Ctrl+Click to delete",
         "Kliko për të rikthyer fotografinë {n} · Ctrl+klik për të fshirë"),
        ("Failed to delete snapshot, please try again",
         "Fshirja e fotografisë dështoi, provo përsëri"),
        ("Snapshot {n} deleted", "Fotografia {n} u fshi"),
        ("Failed to restore snapshot, please try again",
         "Rikthimi i fotografisë dështoi, provo përsëri"),
        ("Before snapshot {n} restore", "Para rikthimit të fotografisë {n}"),
        ("Restore snapshot {n}? Your current changes will be replaced.",
         "Të rikthehet fotografia {n}? Ndryshimet aktuale do të zëvendësohen."),
        ("Restore Snapshot", "Rikthe fotografinë"),
        ("Restore snapshot {n}", "Rikthe fotografinë {n}"),
        ("Teaching Design", "Projektim mësimor"),
        ("Shared collaboration", "Bashkëpunim i ndarë"),
        ("Share to Community", "Ndaj me komunitetin"),
        ("School collaboration", "Bashkëpunim shkollor"),
        ("Reset to default template", "Rivendos shabllonin standard"),
        ("Export as MG file", "Eksporto si skedar MG"),
        ("Click to edit filename", "Kliko për të ndryshuar emrin e skedarit"),
        ("Collaborate (school or shared)", "Bashkëpunim (shkollë ose i ndarë)"),
        ("Click to manage gallery space", "Kliko për të menaxhuar hapësirën e galerisë"),
        ("Click to save", "Kliko për të ruajtur"),
        ("Wireframe", "Skelet"),
        ("Update text style", "Përditëso stilin e tekstit"),
        ("Update border", "Përditëso kufirin"),
        ("Update background", "Përditëso sfondin"),
        ("Toggle Direction", "Ndrysho drejtimin"),
        ("Soon", "Së shpejti"),
        ("Hot", "Nxehtë"),
        ("Switched back to regular mode", "U kthye në modalitetin e zakonshëm"),
        ("Switched to learning sheet mode", "U kalua në modalitet flete mësimi"),
        ("Substep {n}.2", "Nën-hapi {n}.2"),
        ("Substep {n}.1", "Nën-hapi {n}.1"),
        ("Subpart 2", "Nënpjesa 2"),
        ("Subpart 1", "Nënpjesa 1"),
        ("Vibrant", "I gjallë"),
        ("Simple", "I thjeshtë"),
        ("Creative", "Kreativ"),
        ("Business", "Biznes"),
        ("Style", "Stil"),
        ("Style applied", "Stili u aplikua"),
        ("Step added", "Hapi u shtua"),
        ("Similarity {n}", "Ngjashmëria {n}"),
        ("Opacity", "Tejdukshmëri"),
        ("Node added", "Nyja u shtua"),
        ("New substep", "Nën-hap i ri"),
        ("New subpart", "Nënpjesë e re"),
        ("New step", "Hap i ri"),
        ("New part", "Pjesë e re"),
        ("New Item B", "Element i ri B"),
        ("New Item A", "Element i ri A"),
        ("New effect", "Pasojë e re"),
        ("New child", "Fëmijë i ri"),
        ("New cause", "Shkak i ri"),
        ("New branch", "Degë e re"),
        ("New attribute", "Atribut i ri"),
        ("New association", "Shoqërim i ri"),
        ("Failed to save snapshot, please try again",
         "Ruajtja e fotografisë dështoi, provo përsëri"),
        ("Snapshot {n} saved", "Fotografia {n} u ruajt"),
        ("Please save the diagram first before taking a snapshot",
         "Ruaj fillimisht diagramin para se të bësh një fotografi"),
        ("Double-click or double-tap a node label first, then type with the keyboard",
         "Dykliko ose prek dy herë etiketën e nyjës, pastaj shkruaj me tastierën"),
        ("Close keyboard", "Mbyll tastierën"),
        ("On-screen keyboard synced to your interface language",
         "Tastiera në ekran e sinkronizuar me gjuhën e ndërfaqes"),
        ("Virtual Keyboard", "Tastierë virtuale"),
        ("Save a version of this diagram (max 10)",
         "Ruaj një version të këtij diagrami (maks. 10)"),
        ("Snapshot", "Fotografi"),
        ("More Apps", "Më shumë aplikacione"),
        ("Select across batch nodes; make divergent and convergent thinking visible",
         "Zgjidh nyje në grup; bëj të dukshëm mendimin divergjent dhe konvergjent"),
        ("Waterfall", "Ujëvarë"),
        ("Random blanks for study and review",
         "Hapësira të rastit për studim dhe përsëritje"),
        ("Learning sheet", "Fletë mësimi"),
        ("Standard mode now; more modes coming soon",
         "Modaliteti standard tani; më shumë modalitete së shpejti"),
        ("Concept map modes", "Modalitetet e hartës konceptuale"),
        ("Learning sheet restored", "Fleta e mësimit u rikthye"),
        ("Layout direction toggled", "Drejtimi i paraqitjes u ndryshua"),
        ("Format Painter", "Kopjues formatimi"),
        ("Format", "Format"),
        ("Please select a source node first", "Zgjidh fillimisht një nyjë burim"),
        ("Format painter is in development", "Kopjuesi i formatimit është në zhvillim"),
        ("Format painter cancelled", "Kopjuesi i formatimit u anulua"),
        ("Format applied to {count} node(s)", "Formati u aplikua në {count} nyjë(a)"),
        ("Style copied — select target nodes and click again to apply",
         "Stili u kopjua — zgjidh nyjet e synuara dhe kliko përsëri për ta aplikuar"),
        ("English", "Anglisht"),
        ("Chinese", "Kinezisht"),
        ("{name} is in development", "{name} është në zhvillim"),
        ("Highlighter color", "Ngjyra e theksuesit"),
        ("Exit presentation", "Dil nga prezantimi"),
        ("Clear highlighter", "Pastro theksuesin"),
        ("Spotlight", "Spotlight"),
        ("Laser pointer", "Tregues lazer"),
        ("Exit", "Dil"),
        ("Reset", "Rivendos"),
        ("Pause", "Pauzë"),
        ("Start", "Nis"),
        ("Set", "Cakto"),
        ("Minutes", "Minuta"),
        ("Presentation timer", "Kohëmatës prezantimi"),
        ("Timer", "Kohëmatës"),
        ("Pen", "Stilolaps"),
        ("Highlighter", "Theksues"),
        ("Presentation tools", "Mjete prezantimi"),
        ("Photosynthesis", "Fotosintezë"),
        ("Respiration", "Frymëmarrje"),
        ("Rusting", "Ndrydhje"),
        ("Limewater test", "Prova me ujë gëlqeror"),
        ("NH₃ synthesis", "Sintezë NH₃"),
        ("Benzene", "Benzen"),
        ("Urea", "Ure"),
        ("Ammonium nitrate", "Nitrat amoni"),
        ("Bleach", "Zbardhës"),
        ("Vinegar", "Uthull"),
        ("Chalk", "Shkumës"),
        ("Gypsum", "Gips"),
        ("Sphere SA", "Sipërfaqja e sferës"),
        ("3D distance", "Distanca 3D"),
        ("Rect. prism SA", "Sipërfaqja e prizmës drejtkëndëshe"),
        ("Circle sector", "Sektor rrethor"),
        ("Trapezoid", "Trapez"),
        ("Midpoint", "Pika e mesme"),
        ("Point–slope", "Pikë–drejtim"),
        ("Distance", "Distancë"),
        ("Slope m", "Pjerrësia m"),
        ("Difference of squares", "Diferenca e katrorëve"),
        ("Quadratic formula", "Formula kuadratike"),
        ("Sequences · combinatorics · stats",
         "Progresione · kombinatorikë · statistikë"),
        ("Trigonometry · identities", "Trigonometri · identitete"),
        ("Geometry · area & volume", "Gjeometri · sipërfaqe dhe vëllim"),
        ("Algebra · coordinate & line", "Algjeber · koordinata dhe vijë"),
        ("Ions · salts · acids", "Jone · kripëra · acide"),
        ("Molecules · states · reactions", "Molekula · gjendje · reaksione"),
        ("Greek · sums & calculus", "Greqisht · shuma dhe kalkulus"),
        ("Trig · logs & exp", "Trig · log dhe exp"),
        ("Algebra · fractions & roots", "Algjeber · thyesa dhe rrënjë"),
        ("Basic · numbers & compare", "Bazë · numra dhe krahasim"),
        ("K-12 chem formulas", "Formula kimie K–12"),
        ("K-12 equations", "Ekuacione K–12"),
        ("K-12 math", "Matematikë K–12"),
        ("Loading math editor…", "Po ngarkohet redaktori i matematikës…"),
        ("Insert equation", "Fut ekuacionin"),
        ("Insert inline math ($...$) at the caret, or append to the selected node if not editing",
         "Fut matematikë në linjë ($...$) te kursori, ose shto te nyja e zgjedhur nëse nuk po redakton"),
        ("Choose highlighter color", "Zgjidh ngjyrën e theksuesit"),
        ("Draw on the canvas like a highlighter; cleared when you exit presentation",
         "Vizato në kanavacë si me theksues; fshihet kur del nga prezantimi"),
        ("Exit Fullscreen", "Dil nga ekrani i plotë"),
        ("Effect node added", "Nyja e pasojës u shtua"),
        ("Direction", "Drejtim"),
        ("Difference pair added", "Çifti i ndryshimeve u shtua"),
        ("Difference B{n}", "Ndryshimi B{n}"),
        ("Difference A{n}", "Ndryshimi A{n}"),
        ("Deleted {count} node(s)", "U fshinë {count} nyjë(a)"),
        ("Deleted {count} attribute(s)", "U fshinë {count} atribut(e)"),
        ("Deleted {count} analogy pair(s)", "U fshinë {count} çift(e) analogjie"),
        ("Delete nodes", "Fshi nyjet"),
        ("Delete Node", "Fshi nyjën"),
        ("Delete Attribute", "Fshi atributin"),
        ("Delete Analogy Pair", "Fshi çiftin analogjik"),
        ("Please create a diagram first", "Krijo fillimisht një diagram"),
        ("Concept map modes are in development",
         "Modalitetet e hartës konceptuale janë në zhvillim"),
        ("Concept Generation", "Gjenerim konceptesh"),
        ("Only the diagram owner can use AI generation during collaboration",
         "Vetëm pronari i diagramit mund të përdorë gjenerimin me IA gjatë bashkëpunimit"),
        ("Child added", "Fëmija u shtua"),
        ("Cause node added", "Nyja e shkakut u shtua"),
        ("Cannot generate", "Nuk mund të gjenerohet"),
        ("Cannot delete selected node(s)", "Nuk mund të fshihen nyjet e zgjedhura"),
        ("Cannot delete event node", "Nuk mund të fshihet nyja e ngjarjes"),
        ("Cannot delete dimension label", "Nuk mund të fshihet etiketa e dimensionit"),
        ("Cannot add child", "Nuk mund të shtohet fëmijë"),
        ("Branch added", "Degë u shtua"),
        ("Width", "Gjerësi"),
        ("Style", "Stil"),
        ("Border", "Kufi"),
        ("Background Color", "Ngjyra e sfondit"),
        ("Attribute added", "Atributi u shtua"),
        ("Applied", "U aplikua"),
        ("Analogy pair added", "Çifti analogjik u shtua"),
        ("Align", "Rreshto"),
        ("Generating…", "Po gjenerohet…"),
        ("AI Generate", "Gjenero me IA"),
        ("Add Substep", "Shto nën-hap"),
        ("Add Step", "Shto hap"),
        ("Add", "Shto"),
        ("Add Pair", "Shto çift"),
        ("Add node is in development", "Shtimi i nyjës është në zhvillim"),
        ("Add node", "Shto nyjë"),
        ("Add effect", "Shto pasojë"),
        ("Add cause", "Shto shkak"),
        ("Add Attribute", "Shto atribut"),
        ("Add Analogy Pair", "Shto çift analogjie"),
        ("Cannot reset: select a diagram type first",
         "Nuk mund të rivendoset: zgjidh fillimisht një lloj diagrami"),
        ("Reset to Default", "Rivendos në standard"),
        ("Reset", "Rivendos"),
        (
            "Are you sure? All current content will be lost, including the "
            "diagram and node palette. This cannot be undone.",
            "Je i sigurt? Gjithë përmbajtja aktuale do të humbasë, përfshirë "
            "diagramin dhe paletën e nyjeve. Kjo nuk kthehet mbrapsht.",
        ),
        ("Failed to parse diagram file, please try again",
         "Skedari i diagramit nuk u analizua, provo përsëri"),
        ("Invalid diagram file. Please select an MG file exported from MindGraph.",
         "Skedar diagrami i pavlefshëm. Zgjidh një skedar MG të eksportuar nga MindGraph."),
        ("Unknown export format: {format}", "Format i panjohur eksporti: {format}"),
        ("SVG export failed, please try again", "Eksporti SVG dështoi, provo përsëri"),
        ("SVG exported successfully", "SVG u eksportua me sukses"),
        ("PNG export failed, please try again", "Eksporti PNG dështoi, provo përsëri"),
        ("PNG exported successfully", "PNG u eksportua me sukses"),
        ("PDF export failed, please try again", "Eksporti PDF dështoi, provo përsëri"),
        ("PDF exported successfully", "PDF u eksportua me sukses"),
        ("No diagram data to export", "Nuk ka të dhëna diagrami për eksport"),
        ("MG file exported successfully", "Skedari MG u eksportua me sukses"),
        ("MG file export failed, please try again", "Eksporti i skedarit MG dështoi, provo përsëri"),
        ("Cannot export: canvas not ready", "Nuk mund të eksportohet: kanavaca nuk është gati"),
        ("New Subpart 2", "Nënpjesë e re 2"),
        ("New Subpart 1", "Nënpjesë e re 1"),
        ("Delete", "Fshi"),
        ("Edit", "Ndrysho"),
        ("Paste", "Ngjit"),
        ("Copy", "Kopjo"),
        ("New idea", "Ide e re"),
        ("Add to this group", "Shto në këtë grup"),
        ("Add node", "Shto nyjë"),
        ("Add effect", "Shto pasojë"),
        ("Add concept", "Shto koncept"),
        ("Add child", "Shto fëmijë"),
        ("Add cause", "Shto shkak"),
        ("Add branch", "Shto degë"),
        ("Add attribute", "Shto atribut"),
        ("New item B", "Element i ri B"),
        ("New item A", "Element i ri A"),
        ("Enter", "Hyr"),
        ("'s root concept", " — koncepti rrënjë"),
        ("Root concept", "Koncept rrënjë"),
        ("Other possible classification dimensions for this topic:",
         "Dimensione të tjera të mundshme klasifikimi për këtë temë:"),
        ("Other possible analogy patterns for this topic:",
         "Modele të tjera të mundshme analogjie për këtë temë:"),
        ("Other possible decomposition dimensions for this topic:",
         "Dimensione të tjera të mundshme të dekompozimit për këtë temë:"),
        ("Exit fullscreen", "Dil nga ekrani i plotë"),
        ("Fit canvas", "Përshtat kanavacën"),
        ("Fullscreen", "Ekran i plotë"),
        ("Show presentation tools", "Shfaq mjetet e prezantimit"),
        ("Hide presentation tools", "Fshih mjetet e prezantimit"),
        ("Collaboration", "Bashkëpunim"),
        ("Joined: {title}", "U bashkua: {title}"),
        ("Joined presentation: {title}", "U bashkua me prezantimin: {title}"),
        ("Join", "Bashkohu"),
        ("Import", "Importo"),
        ("Collaborate", "Bashkëpunoj"),
        ("Cancel", "Anulo"),
        ("Export", "Eksporto"),
        ("Back", "Prapa"),
        ("Undo", "Zhbëj"),
        ("Redo", "Ribëj"),
        ("Text", "Tekst"),
        ("Delete", "Fshi"),
        ("Insert", "Fut"),
        ("Cancel", "Anulo"),
        ("Select a node first", "Zgjidh fillimisht një nyjë"),
        ("Chemistry", "Kimi"),
        ("Classification by", "Klasifikim sipas"),
        ("Decomposition by", "Dekompozim sipas"),
        ("Enter text…", "Shkruaj tekstin…"),
        ("Answers:", "Përgjigje:"),
        ("relates to", "lidhet me"),
        ("Sub-item", "Nën-element"),
        ("New similarity", "Ngjashmëri e re"),
        ("Right Difference", "Ndryshim në të djathtë"),
        ("New Part", "Pjesë e re"),
        ("Left Difference", "Ndryshim në të majtë"),
        ("New Item", "Element i ri"),
        ("New Effect", "Pasojë e re"),
        ("New Context", "Kontekst i ri"),
        ("New Concept", "Koncept i ri"),
        ("New Child", "Fëmijë i ri"),
        ("New Cause", "Shkak i ri"),
        ("New Category", "Kategori e re"),
        ("New Right", "E djathtë e re"),
        ("New Left", "E majta e re"),
        ("New Branch", "Degë e re"),
        ("New Attribute", "Atribut i ri"),
        ("Analogy relationship:", "Marrëdhënia analogjike:"),
        ("Relationship", "Marrëdhënie"),
        ("Main Event", "Ngjarja kryesore"),
        ("Central Topic", "Tema qendrore"),
        ("Category {n}", "Kategoria {n}"),
        ("Cause {n}", "Shkaku {n}"),
        ("Effect {n}", "Pasoja {n}"),
        ("Root Topic", "Tema rrënjë"),
        ("Process", "Proces"),
        ("Part {n}", "Pjesa {n}"),
        ("Item {n}.{m}", "Elementi {n}.{m}"),
        ("Context {n}", "Konteksti {n}"),
        ("Child {n}.{m}", "Fëmija {n}.{m}"),
        ("Topic", "Temë"),
        ("Topic A", "Tema A"),
        ("Topic B", "Tema B"),
        ("Attribute {n}", "Atributi {n}"),
        ("Branch {n}", "Degë {n}"),
        ("Item A{n}", "Elementi A{n}"),
        ("Item B{n}", "Elementi B{n}"),
        ("Subpart {n}.{m}", "Nënpjesa {n}.{m}"),
        ("Substep {n}.{m}", "Nën-hapi {n}.{m}"),
        ("Step {n}", "Hapi {n}"),
        ("Saving…", "Duke ruajtur…"),
        ("Unsaved changes", "Ndryshime të paruajtura"),
        ("Saved", "U ruajt"),
        ("{n} online", "{n} në linjë"),
        ("Classification", "Klasifikim"),
        ("Event", "Ngjarje"),
        ("Item A", "Elementi A"),
        ("Item B", "Elementi B"),
        ("Subject", "Lëndë"),
        ("Theme", "Temë"),
        ("Center topic", "Tema qendrore"),
        ("Analogy relation", "Marrëdhënie analogjie"),
        ("Please select a step to add substep to",
         "Zgjidh një hap ku të shtosh nën-hapin"),
        ("Please select a similarity or difference node first",
         "Zgjidh fillimisht një nyjë ngjashmërie ose ndryshimi"),
        ("Please select similarity or difference nodes (topic nodes cannot be deleted)",
         "Zgjidh nyje ngjashmërie ose ndryshimi (nyjet e temës nuk fshihen)"),
        ("Select a part node, then press Enter to add subpart",
         "Zgjidh një nyjë pjese, pastaj shtyp Enter për të shtuar nënpjesë"),
        ("Please select a part to add subpart to",
         "Zgjidh një pjesë ku të shtosh nënpjesën"),
        ("Please select node(s) to delete", "Zgjidh nyjet për t’i fshirë"),
        ("Please select node(s) first", "Zgjidh fillimisht nyje(t)"),
        ("Please select category or leaf nodes (topic node cannot be deleted)",
         "Zgjidh nyje kategorie ose gjethe (nyja e temës nuk fshihet)"),
        ("Please select a branch or child node", "Zgjidh një degë ose nyjë fëmijë"),
        ("Presets", "Paracaktuar"),
        ("Part added", "Pjesa u shtua"),
        ("Please select a similarity or difference node first",
         "Zgjidh fillimisht një nyjë ngjashmërie ose ndryshimi"),
        ("Add node feature coming soon", "Veçoria e shtimit të nyjës së shpejti"),
        ("Please create a diagram first", "Krijo fillimisht një diagram"),
        ("Cannot delete topic node", "Nuk mund të fshihet nyja e temës"),
        ("Color", "Ngjyrë"),
        ("Common compounds & salts", "Përzierje të zakonshme dhe kripëra"),
        ("Classic reactions", "Reaksione klasike"),
        ("Acids · organics · labs", "Acide · organike · laboratorë"),
        ("Double angle", "Kënd i dyfishtë"),
        ("Arithmetic aₙ", "Progresion aritmetik aₙ"),
        ("Geometric aₙ", "Progresion gjeometrik aₙ"),
        ("Geometric sum", "Shuma gjeometrike"),
        ("Binomial theorem", "Teorema binomiale"),
        ("Mean x̄", "Mesatarja x̄"),
        ("σ² (population)", "σ² (popullatë)"),
        ("Font", "Shkrimi"),
        ("New Step", "Hap i ri"),
        ("New Subpart", "Nënpjesë e re"),
        ("New Substep", "Nën-hap i ri"),
        ("Subpart added", "Nënpjesa u shtua"),
        ("Substep added", "Nën-hapi u shtua"),
        ("Restore", "Rikthe"),
        ("New concept", "Koncept i ri"),
        ("New Similarity", "Ngjashmëri e re"),
        ("Save Diagram", "Ruaj diagramin"),
        ("Zoom In", "Zmadho"),
        ("Zoom Out", "Zvogëlo"),
        ("Network error", "Gabim rrjeti"),
        ("Add analogy pair", "Shto çift analogjie"),
        ("Add cause", "Shto shkak"),
        ("Add effect", "Shto pasojë"),
        ("Analogy pair added", "Çifti analogjik u shtua"),
        ("Applied", "U aplikua"),
        ("Attribute added", "Atributi u shtua"),
        ("Border", "Kufi"),
        ("Style", "Stil"),
        ("Width", "Gjerësi"),
        ("Branch added", "Degë u shtua"),
        ("Cannot add child", "Nuk mund të shtohet fëmijë"),
        ("Cannot delete dimension label", "Nuk mund të fshihet etiketa e dimensionit"),
        ("Cannot delete event node", "Nuk mund të fshihet nyja e ngjarjes"),
        ("Cannot delete selected node(s)", "Nuk mund të fshihen nyjet e zgjedhura"),
        ("Cannot generate", "Nuk mund të gjenerohet"),
        ("Cause node added", "Nyja e shkakut u shtua"),
        ("Child added", "Fëmija u shtua"),
        ("Direction", "Drejtim"),
        ("Difference A{n}", "Ndryshimi A{n}"),
        ("Difference B{n}", "Ndryshimi B{n}"),
        ("Difference pair added", "Çifti i ndryshimeve u shtua"),
        ("Effect node added", "Nyja e pasojës u shtua"),
        ("Exit", "Dil"),
        ("Exit Fullscreen", "Dil nga ekrani i plotë"),
        ("Draw on the canvas like a highlighter; cleared when you exit presentation",
         "Vizato në kanavacë si me theksues; pastrohet kur del nga prezantimi"),
        ("Choose highlighter color", "Zgjidh ngjyrën e theksuesit"),
        ("Select a node first", "Zgjidh fillimisht një nyjë"),
        ("Loading math editor…", "Po ngarkohet redaktori i matematikës…"),
        ("K-12 math", "Matematikë K–12"),
        ("K-12 equations", "Ekuacione K–12"),
        ("K-12 chem formulas", "Formula kimie K–12"),
        ("Chemistry", "Kimi"),
        ("Basic · numbers & compare", "Bazë · numra dhe krahasim"),
        ("Algebra · fractions & roots", "Algjeber · thyesa dhe rrënjë"),
        ("Trig · logs & exp", "Trig · log dhe eksponentë"),
        ("Greek · sums & calculus", "Greqisht · shuma dhe kalkulus"),
        ("Molecules · states · reactions", "Molekula · gjendje · reaksione"),
    ]
    return apply_pairs(value, pairs)


def to_arabic(value: str) -> str:
    pairs: list[tuple[str, str]] = [
        ("Hello {username}, I'm your AI visual thinking assistant",
         "مرحبًا {username}، أنا مساعدك للتفكير البصري بالذكاء الاصطناعي"),
        ("Enter the invitation code (xxx-xxx) to join their session.",
         "أدخل رمز الدعوة (xxx-xxx) للانضمام إلى جلستهم."),
        ("No school sessions right now. A colleague must start “School collaboration” on the canvas.",
         "لا توجد جلسات مدرسية نشطة الآن. يجب على زميل بدء «التعاون المدرسي» على اللوحة."),
        ("Network error, failed to join", "خطأ في الشبكة، فشل الانضمام"),
        ("Could not load school sessions", "تعذّر تحميل الجلسات المدرسية"),
        ("Failed to join presentation", "فشل الانضمام إلى العرض"),
        ("Failed to join", "فشل الانضمام"),
        ("Describe your diagram, or choose a template below...",
         "صف مخططك أو اختر قالبًا أدناه..."),
        ("Describe your diagram, or choose a template below…",
         "صف مخططك أو اختر قالبًا أدناه…"),
        ("Please enter the complete presentation code", "يرجى إدخال رمز العرض الكامل"),
        ("Invalid presentation code format (should be xxx-xxx)",
         "تنسيق رمز العرض غير صالح (يجب أن يكون xxx-xxx)"),
        ("Create on canvas", "أنشئ على اللوحة"),
        ("Classify & group", "صنّف ومجّمِع"),
        ("Cause & effect", "السبب والأثر"),
        ("Organize ideas", "نظّم الأفكار"),
        ("Sequence & steps", "التسلسل والخطوات"),
        ("Compare & contrast", "قارن وقابِل"),
        ("Concept relations", "علاقات المفاهيم"),
        ("Brainstorm & associate", "عصف ذهني وربط"),
        ("Describe attributes", "صف السمات"),
        ("Analogies", "تشبيهات"),
        ("Whole & parts", "الكل والأجزاء"),
        ("Tree Map", "خريطة شجرة"),
        ("Multi-Flow Map", "خريطة تدفق متعدد"),
        ("Mind Map", "خريطة ذهنية"),
        ("Flow Map", "خريطة تدفق"),
        ("Double Bubble Map", "خريطة فقاعات مزدوجة"),
        ("Concept Map", "خريطة مفاهيم"),
        ("Circle Map", "خريطة دائرية"),
        ("Bubble Map", "خريطة فقاعات"),
        ("Bridge Map", "خريطة جسر"),
        ("Brace Map", "خريطة أقواس"),
        ("Choose a diagram type", "اختر نوع المخطط"),
        ("Space full, auto-save not available at the moment. Please delete existing diagrams to free more space.",
         "المساحة ممتلئة؛ الحفظ التلقائي غير متاح حاليًا. احذف المخططات الحالية لتحرير مساحة."),
        ("Select Diagram Type", "اختر نوع المخطط"),
        ("New Diagram", "مخطط جديد"),
        ("Fit to Screen", "ملاءمة الشاشة"),
        ("Export Image", "تصدير صورة"),
        ("Please log in to save", "يرجى تسجيل الدخول للحفظ"),
        ("Saved {n}min ago", "تم الحفظ قبل {n} د"),
        ("Saved {n}s ago", "تم الحفظ قبل {n} ث"),
        ("Saved just now", "تم الحفظ للتو"),
        ("Saved at {time}", "تم الحفظ في {time}"),
        ("Enter relationship...", "أدخل العلاقة..."),
        ("Press 1–5 to select", "اضغط 1–5 للاختيار"),
        ("click to specify...", "انقر للتحديد..."),
        ("[Click to set]", "[انقر للتعيين]"),
        ("Focus question: ", "سؤال التركيز: "),
        ("[Alternatives will appear here]", "[ستظهر البدائل هنا]"),
        ("AI...", "ذكاء اصطناعي..."),
        ("Validation request failed", "فشل طلب التحقق"),
        ("No result", "لا نتيجة"),
        ("Hand tool", "أداة اليد"),
        ("Click to restore snapshot {n} · Ctrl+Click to delete",
         "انقر لاستعادة اللقطة {n} · Ctrl+انقر للحذف"),
        ("Failed to delete snapshot, please try again",
         "فشل حذف اللقطة، حاول مرة أخرى"),
        ("Snapshot {n} deleted", "تم حذف اللقطة {n}"),
        ("Failed to restore snapshot, please try again",
         "فشل استعادة اللقطة، حاول مرة أخرى"),
        ("Before snapshot {n} restore", "قبل استعادة اللقطة {n}"),
        ("Restore snapshot {n}? Your current changes will be replaced.",
         "استعادة اللقطة {n}؟ سيتم استبدال تغييراتك الحالية."),
        ("Restore Snapshot", "استعادة لقطة"),
        ("Restore snapshot {n}", "استعادة اللقطة {n}"),
        ("Teaching Design", "تصميم تدريسي"),
        ("Shared collaboration", "تعاون مشترك"),
        ("Share to Community", "شارك مع المجتمع"),
        ("School collaboration", "تعاون مدرسي"),
        ("Reset to default template", "إعادة تعيين القالب الافتراضي"),
        ("Export as MG file", "تصدير كملف MG"),
        ("Click to edit filename", "انقر لتحرير اسم الملف"),
        ("Collaborate (school or shared)", "تعاون (مدرسي أو مشترك)"),
        ("Click to manage gallery space", "انقر لإدارة مساحة المعرض"),
        ("Click to save", "انقر للحفظ"),
        ("Wireframe", "إطار سلكي"),
        ("Update text style", "تحديث نمط النص"),
        ("Update border", "تحديث الحدود"),
        ("Update background", "تحديث الخلفية"),
        ("Toggle Direction", "تبديل الاتجاه"),
        ("Soon", "قريبًا"),
        ("Hot", "رائج"),
        ("Switched back to regular mode", "عُدت إلى الوضع العادي"),
        ("Switched to learning sheet mode", "تم التبديل إلى وضع ورقة التعلم"),
        ("Cannot export: canvas not ready", "لا يمكن التصدير: اللوحة غير جاهزة"),
        ("MG file export failed, please try again", "فشل تصدير ملف MG، حاول مرة أخرى"),
        ("MG file exported successfully", "تم تصدير ملف MG بنجاح"),
        ("No diagram data to export", "لا توجد بيانات مخطط للتصدير"),
        ("PDF export failed, please try again", "فشل تصدير PDF، حاول مرة أخرى"),
        ("PDF exported successfully", "تم تصدير PDF بنجاح"),
        ("PNG export failed, please try again", "فشل تصدير PNG، حاول مرة أخرى"),
        ("PNG exported successfully", "تم تصدير PNG بنجاح"),
        ("SVG export failed, please try again", "فشل تصدير SVG، حاول مرة أخرى"),
        ("SVG exported successfully", "تم تصدير SVG بنجاح"),
        ("Unknown export format: {format}", "تنسيق تصدير غير معروف: {format}"),
        ("Invalid diagram file. Please select an MG file exported from MindGraph.",
         "ملف مخطط غير صالح. يرجى اختيار ملف MG مُصدَّر من MindGraph."),
        ("Failed to parse diagram file, please try again",
         "فشل تحليل ملف المخطط، حاول مرة أخرى"),
        (
            "Are you sure? All current content will be lost, including the "
            "diagram and node palette. This cannot be undone.",
            "هل أنت متأكد؟ ستفقد كل المحتوى الحالي بما في ذلك المخطط ولوحة "
            "العقد. لا يمكن التراجع.",
        ),
        ("Reset", "إعادة تعيين"),
        ("Reset to Default", "إعادة تعيين للافتراضي"),
        ("Cannot reset: select a diagram type first",
         "لا يمكن الإعادة: اختر نوع المخطط أولًا"),
        ("Add Analogy Pair", "إضافة زوج تشبيه"),
        ("Add Attribute", "إضافة سمة"),
        ("Add Cause", "إضافة سبب"),
        ("Add Effect", "إضافة أثر"),
        ("Add Node", "إضافة عقدة"),
        ("Add node", "إضافة عقدة"),
        ("Add node is in development", "إضافة العقدة قيد التطوير"),
        ("Add Pair", "إضافة زوج"),
        ("Add Step", "إضافة خطوة"),
        ("Add Substep", "إضافة خطوة فرعية"),
        ("AI Generate", "توليد بالذكاء الاصطناعي"),
        ("Generating…", "جارٍ التوليد…"),
        ("Align", "محاذاة"),
        ("Delete", "حذف"),
        ("Cancel", "إلغاء"),
        ("Insert", "إدراج"),
        ("Copy", "نسخ"),
        ("Paste", "لصق"),
        ("Edit", "تحرير"),
        ("Export", "تصدير"),
        ("Import", "استيراد"),
        ("Back", "رجوع"),
        ("Collaboration", "تعاون"),
        ("Join", "انضمام"),
        ("Collaborate", "تعاون"),
        ("Cancel", "إلغاء"),
        ("Only the diagram owner can use AI generation during collaboration",
         "يمكن لمالك المخطط فقط استخدام التوليد بالذكاء الاصطناعي أثناء التعاون"),
        ("Presentation tools", "أدوات العرض"),
        ("Highlighter", "تمييز"),
        ("Laser pointer", "مؤشر ليزر"),
        ("Exit presentation", "الخروج من العرض"),
        ("{name} is in development", "{name} قيد التطوير"),
        ("English", "الإنجليزية"),
        ("Chinese", "الصينية"),
        ("Font", "خط"),
        ("Color", "لون"),
        ("Undo", "تراجع"),
        ("Redo", "إعادة"),
        ("Zoom In", "تكبير"),
        ("Zoom Out", "تصغير"),
        ("Saving…", "جارٍ الحفظ…"),
        ("Unsaved changes", "تغييرات غير محفوظة"),
        ("Saved", "تم الحفظ"),
        ("New Subpart 1", "جزء فرعي جديد 1"),
        ("New Subpart 2", "جزء فرعي جديد 2"),
        ("Add cause", "إضافة سبب"),
        ("Add effect", "إضافة أثر"),
        ("Analogy pair added", "أُضيف زوج تشبيه"),
        ("Applied", "تم التطبيق"),
        ("Attribute added", "أُضيفت سمة"),
        ("BG", "خلفية"),
        ("Border", "حدود"),
        ("Style", "نمط"),
        ("Width", "عرض"),
        ("Branch added", "أُضيف فرع"),
        ("Cannot add child", "لا يمكن إضافة فرع فرعي"),
        ("Cannot delete dimension label", "لا يمكن حذف تسمية البعد"),
        ("Cannot delete event node", "لا يمكن حذف عقدة الحدث"),
        ("Cannot delete selected node(s)", "لا يمكن حذف العقد المحددة"),
        ("Cannot delete topic node", "لا يمكن حذف عقدة الموضوع"),
        ("Cannot generate", "لا يمكن التوليد"),
        ("Cause node added", "أُضيفت عقدة السبب"),
        ("Child added", "أُضيف فرع"),
        ("Concept Generation", "توليد المفاهيم"),
        ("Concept map modes are in development",
         "أنماط خريطة المفاهيم قيد التطوير"),
        ("Please create a diagram first", "يرجى إنشاء مخطط أولًا"),
        ("Difference A{n}", "الفرق A{n}"),
        ("Difference B{n}", "الفرق B{n}"),
        ("Difference pair added", "أُضيف زوج الفروقات"),
        ("Direction", "الاتجاه"),
        ("Effect node added", "أُضيفت عقدة الأثر"),
        ("Exit", "خروج"),
        ("Exit Fullscreen", "الخروج من ملء الشاشة"),
        ("Draw on the canvas like a highlighter; cleared when you exit presentation",
         "ارسم على اللوحة كالقلم المضيء؛ يُمسح عند الخروج من العرض"),
        ("Choose highlighter color", "اختر لون التمييز"),
        ("Select a node first", "اختر عقدة أولًا"),
        ("Loading math editor…", "جارٍ تحميل محرر الرياضيات…"),
        ("K-12 math", "رياضيات K–12"),
        ("K-12 equations", "معادلات K–12"),
        ("K-12 chem formulas", "صيغ كيميائية K–12"),
        ("Chemistry", "كيمياء"),
        ("Basic · numbers & compare", "أساسي · أعداد ومقارنة"),
        ("Algebra · fractions & roots", "جبر · كسور وجذور"),
        ("Trig · logs & exp", "مثلثات · لوغاريتمات وأسس"),
        ("Greek · sums & calculus", "يوناني · مجموعات وتفاضل"),
        ("Molecules · states · reactions", "جزيئات · حالات · تفاعلات"),
        ("Ions · salts · acids", "أيونات · أملاح · أحماض"),
        ("Algebra · coordinate & line", "جبر · إحداثيات وخط"),
        ("Geometry · area & volume", "هندسة · مساحة وحجم"),
        ("Trigonometry · identities", "مثلثات · هويات"),
        ("Sequences · combinatorics · stats",
         "متتاليات · توافقيات · إحصاء"),
        ("Common compounds & salts", "مركبات وأملاح شائعة"),
        ("Classic reactions", "تفاعلات كلاسيكية"),
        ("Acids · organics · labs", "أحماض · عضوية · مختبرات"),
        ("Quadratic formula", "صيغة المعادلة التربيعية"),
        ("Difference of squares", "فرق بين مربعين"),
        ("Slope m", "الميل m"),
        ("Distance", "مسافة"),
        ("Point–slope", "نقطة–ميل"),
        ("Midpoint", "نقطة منتصف"),
        ("Trapezoid", "شبه منحرف"),
        ("Circle sector", "قطاع دائرة"),
        ("Sphere SA", "مساحة سطح الكرة"),
        ("3D distance", "مسافة ثلاثية الأبعاد"),
        ("Rect. prism SA", "مساحة سطح منشور مستطيل"),
        ("Law of cosines", "قانون جيب التمام"),
        ("Law of sines", "قانون الجيب"),
        ("Double angle", "زاوية مضاعفة"),
        ("Arithmetic aₙ", "تسلسل حسابي aₙ"),
        ("Geometric aₙ", "تسلسل هندسي aₙ"),
        ("Geometric sum", "مجموع هندسي"),
        ("Binomial theorem", "مبرهنة ذات الحدين"),
        ("Mean x̄", "متوسط x̄"),
        ("σ² (population)", "σ² (مجتمع)"),
        ("Photosynthesis", "تمثيل ضوئي"),
        ("Respiration", "تنفس خلوي"),
        ("Rusting", "صدأ"),
        ("Limewater test", "اختبار ماء الجير"),
        ("NH₃ synthesis", "تحضير NH₃"),
        ("Benzene", "بنزين"),
        ("Urea", "يوريا"),
        ("Ammonium nitrate", "نترات الأمونيوم"),
        ("Bleach", "مبيّض"),
        ("Vinegar", "خل"),
        ("Chalk", "طباشير"),
        ("Gypsum", "جبس"),
        ("Pen", "قلم"),
        ("Spotlight", "بقعة ضوء"),
        ("Timer", "مؤقت"),
        ("Presentation timer", "مؤقت العرض"),
        ("Minutes", "دقائق"),
        ("Set", "تعيين"),
        ("Start", "بدء"),
        ("Pause", "إيقاف مؤقت"),
        ("Clear highlighter", "مسح التمييز"),
        ("Style copied — select target nodes and click again to apply",
         "نُسخ النمط — حدد العقد المستهدفة وانقر مجددًا للتطبيق"),
        ("Format applied to {count} node(s)",
         "طُبّق التنسيق على {count} عقدة"),
        ("Format painter cancelled", "أُلغي ناسخ التنسيق"),
        ("{n} online", "{n} متصل"),
    ]
    return apply_pairs(value, pairs)


def to_hindi(value: str) -> str:
    pairs: list[tuple[str, str]] = [
        ("Hello {username}, I'm your AI visual thinking assistant",
         "नमस्ते {username}, मैं आपका AI दृश्य सोच सहायक हूँ"),
        ("Enter the invitation code (xxx-xxx) to join their session.",
         "उनके सत्र में शामिल होने के लिए आमंत्रण कोड (xxx-xxx) दर्ज करें।"),
        ("No school sessions right now. A colleague must start “School collaboration” on the canvas.",
         "अभी कोई स्कूल सत्र सक्रिय नहीं है। किसी सहकर्मी को कैनवास पर «स्कूल सहयोग» शुरू करना होगा।"),
        ("Network error, failed to join", "नेटवर्क त्रुटि, शामिल होना विफल"),
        ("Could not load school sessions", "स्कूल सत्र लोड नहीं हो सके"),
        ("Failed to join presentation", "प्रस्तुति में शामिल होना विफल"),
        ("Failed to join", "शामिल होना विफल"),
        ("Describe your diagram, or choose a template below...",
         "अपना आरेख वर्णन करें, या नीचे एक टेम्पलेट चुनें..."),
        ("Describe your diagram, or choose a template below…",
         "अपना आरेख वर्णन करें, या नीचे एक टेम्पलेट चुनें…"),
        ("Please enter the complete presentation code", "कृपया पूरा प्रस्तुति कोड दर्ज करें"),
        ("Invalid presentation code format (should be xxx-xxx)",
         "अमान्य प्रस्तुति कोड प्रारूप (xxx-xxx होना चाहिए)"),
        ("Create on canvas", "कैनवास पर बनाएँ"),
        ("Classify & group", "वर्गीकृत करें और समूहित करें"),
        ("Cause & effect", "कारण और प्रभाव"),
        ("Organize ideas", "विचार व्यवस्थित करें"),
        ("Sequence & steps", "क्रम और चरण"),
        ("Compare & contrast", "तुलना और विरोधाभास"),
        ("Concept relations", "अवधारणा संबंध"),
        ("Brainstorm & associate", "मंथन और संबद्ध"),
        ("Describe attributes", "गुण वर्णित करें"),
        ("Analogies", "रूपक"),
        ("Whole & parts", "संपूर्ण और भाग"),
        ("Tree Map", "ट्री मैप"),
        ("Multi-Flow Map", "मल्टी-फ्लो मैप"),
        ("Mind Map", "माइंड मैप"),
        ("Flow Map", "फ्लो मैप"),
        ("Double Bubble Map", "डबल बबल मैप"),
        ("Concept Map", "कॉन्सेप्ट मैप"),
        ("Circle Map", "सर्कल मैप"),
        ("Bubble Map", "बबल मैप"),
        ("Bridge Map", "ब्रिज मैप"),
        ("Brace Map", "ब्रेस मैप"),
        ("Choose a diagram type", "एक आरेख प्रकार चुनें"),
        ("Space full, auto-save not available at the moment. Please delete existing diagrams to free more space.",
         "स्थान भरा है; ऑटो-सेव अभी उपलब्ध नहीं। अधिक स्थान के लिए मौजूदा आरेख हटाएँ।"),
        ("Cannot export: canvas not ready", "निर्यात नहीं कर सकते: कैनवास तैयार नहीं है"),
        ("MG file export failed, please try again", "MG फ़ाइल निर्यात विफल, पुनः प्रयास करें"),
        ("MG file exported successfully", "MG फ़ाइल सफलतापूर्वक निर्यात"),
        ("No diagram data to export", "निर्यात के लिए कोई आरेख डेटा नहीं"),
        ("PDF export failed, please try again", "PDF निर्यात विफल, पुनः प्रयास करें"),
        ("PDF exported successfully", "PDF सफलतापूर्वक निर्यात"),
        ("PNG export failed, please try again", "PNG निर्यात विफल, पुनः प्रयास करें"),
        ("PNG exported successfully", "PNG सफलतापूर्वक निर्यात"),
        ("SVG export failed, please try again", "SVG निर्यात विफल, पुनः प्रयास करें"),
        ("SVG exported successfully", "SVG सफलतापूर्वक निर्यात"),
        ("Unknown export format: {format}", "अज्ञात निर्यात प्रारूप: {format}"),
        ("Invalid diagram file. Please select an MG file exported from MindGraph.",
         "अमान्य आरेख फ़ाइल। कृपया MindGraph से निर्यात की गई MG फ़ाइल चुनें।"),
        ("Failed to parse diagram file, please try again",
         "आरेख फ़ाइल पार्स करने में विफल, पुनः प्रयास करें"),
        (
            "Are you sure? All current content will be lost, including the "
            "diagram and node palette. This cannot be undone.",
            "क्या आप सुनिश्चित हैं? वर्तमान सारी सामग्री खो जाएगी, जिसमें "
            "आरेख और नोड पैलेट शामिल है। इसे पूर्ववत नहीं किया जा सकता।",
        ),
        ("Reset", "रीसेट"),
        ("Reset to Default", "डिफ़ॉल्ट पर रीसेट"),
        ("Cannot reset: select a diagram type first",
         "रीसेट नहीं कर सकते: पहले आरेख प्रकार चुनें"),
        ("Add Node", "नोड जोड़ें"),
        ("Add node", "नोड जोड़ें"),
        ("Delete", "हटाएँ"),
        ("Cancel", "रद्द करें"),
        ("Insert", "डालें"),
        ("Copy", "कॉपी"),
        ("Paste", "पेस्ट"),
        ("Edit", "संपादित करें"),
        ("Export", "निर्यात"),
        ("Import", "आयात"),
        ("Back", "वापस"),
        ("Collaboration", "सहयोग"),
        ("Join", "शामिल हों"),
        ("Collaborate", "सहयोग करें"),
        ("Only the diagram owner can use AI generation during collaboration",
         "सहयोग के दौरान केवल आरेख स्वामी AI जनरेशन उपयोग कर सकता है"),
        ("AI Generate", "AI जनरेट"),
        ("Generating…", "जनरेट हो रहा है…"),
        ("Presentation tools", "प्रस्तुति उपकरण"),
        ("Highlighter", "हाइलाइटर"),
        ("Laser pointer", "लेज़र पॉइंटर"),
        ("Exit presentation", "प्रस्तुति से बाहर निकलें"),
        ("{name} is in development", "{name} विकास में है"),
        ("English", "अंग्रेज़ी"),
        ("Chinese", "चीनी"),
        ("Font", "फ़ॉन्ट"),
        ("Color", "रंग"),
        ("Undo", "पूर्ववत"),
        ("Redo", "फिर करें"),
        ("Zoom In", "ज़ूम इन"),
        ("Zoom Out", "ज़ूम आउट"),
        ("Saving…", "सहेजा जा रहा है…"),
        ("Unsaved changes", "असहेजे परिवर्तन"),
        ("Saved", "सहेजा गया"),
        ("Saved at {time}", "{time} पर सहेजा गया"),
        ("Saved just now", "अभी सहेजा गया"),
        ("Saved {n}s ago", "{n} सेकंड पहले सहेजा गया"),
        ("Saved {n}min ago", "{n} मिनट पहले सहेजा गया"),
        ("Please log in to save", "सहेजने के लिए लॉग इन करें"),
        ("Select Diagram Type", "आरेख प्रकार चुनें"),
        ("New Diagram", "नया आरेख"),
        ("Fit to Screen", "स्क्रीन पर फिट"),
        ("Export Image", "छवि निर्यात"),
        ("Press 1–5 to select", "चुनने के लिए 1–5 दबाएँ"),
        ("Enter text…", "टेक्स्ट दर्ज करें…"),
        ("Answers:", "उत्तर:"),
        ("Root concept", "मूल अवधारणा"),
        ("Relationship", "संबंध"),
        ("Topic", "विषय"),
        ("Process", "प्रक्रिया"),
        ("Fullscreen", "पूर्ण स्क्रीन"),
        ("Exit fullscreen", "पूर्ण स्क्रीन से बाहर"),
        ("New Subpart 1", "नया उप-भाग 1"),
        ("New Subpart 2", "नया उप-भाग 2"),
        ("Add cause", "कारण जोड़ें"),
        ("Add effect", "प्रभाव जोड़ें"),
        ("Analogy pair added", "रूपक युग्म जोड़ा गया"),
        ("Applied", "लागू किया गया"),
        ("Attribute added", "गुण जोड़ा गया"),
        ("BG", "पृष्ठभूमि"),
        ("Border", "सीमा"),
        ("Style", "शैली"),
        ("Width", "चौड़ाई"),
        ("Branch added", "शाखा जोड़ी गई"),
        ("Cannot add child", "उप-नोड नहीं जोड़ सकते"),
        ("Cannot delete dimension label", "माप लेबल नहीं हटा सकते"),
        ("Cannot delete event node", "घटना नोड नहीं हटा सकते"),
        ("Cannot delete selected node(s)", "चयनित नोड नहीं हटा सकते"),
        ("Cannot delete topic node", "विषय नोड नहीं हटा सकते"),
        ("Cannot generate", "जनरेट नहीं कर सकते"),
        ("Cause node added", "कारण नोड जोड़ा गया"),
        ("Child added", "उप-नोड जोड़ा गया"),
        ("Concept Generation", "अवधारणा जनरेशन"),
        ("Concept map modes are in development",
         "कॉन्सेप्ट मैप मोड विकास में हैं"),
        ("Please create a diagram first", "कृपया पहले आरेख बनाएँ"),
        ("Difference A{n}", "अंतर A{n}"),
        ("Difference B{n}", "अंतर B{n}"),
        ("Difference pair added", "अंतर युग्म जोड़ा गया"),
        ("Direction", "दिशा"),
        ("Effect node added", "प्रभाव नोड जोड़ा गया"),
        ("Exit", "बाहर निकलें"),
        ("Exit Fullscreen", "पूर्ण स्क्रीन से बाहर"),
        ("Draw on the canvas like a highlighter; cleared when you exit presentation",
         "कैनवास पर हाइलाइटर की तरह बनाएँ; प्रस्तुति छोड़ने पर साफ हो जाता है"),
        ("Choose highlighter color", "हाइलाइटर रंग चुनें"),
        ("Select a node first", "पहले एक नोड चुनें"),
        ("Loading math editor…", "गणित संपादक लोड हो रहा है…"),
        ("K-12 math", "K–12 गणित"),
        ("K-12 equations", "K–12 समीकरण"),
        ("K-12 chem formulas", "K–12 रसायन सूत्र"),
        ("Chemistry", "रसायन विज्ञान"),
        ("Basic · numbers & compare", "बुनियादी · संख्या और तुलना"),
        ("Algebra · fractions & roots", "बीजगणित · भिन्न और मूल"),
        ("Trig · logs & exp", "त्रिकोणमिति · लघुगणक और घात"),
        ("Greek · sums & calculus", "यूनानी · योग और कलन"),
        ("Molecules · states · reactions", "अणु · अवस्था · अभिक्रियाएँ"),
        ("Ions · salts · acids", "आयन · लवण · अम्ल"),
        ("Algebra · coordinate & line", "बीजगणित · निर्देशांक और रेखा"),
        ("Geometry · area & volume", "ज्यामिति · क्षेत्रफल और आयतन"),
        ("Trigonometry · identities", "त्रिकोणमिति · सर्वसमिकाएँ"),
        ("Sequences · combinatorics · stats",
         "अनुक्रम · संयोजन · आँकड़े"),
        ("Common compounds & salts", "सामान्य यौगिक और लवण"),
        ("Classic reactions", "क्लासिक अभिक्रियाएँ"),
        ("Acids · organics · labs", "अम्ल · कार्बनिक · प्रयोगशाला"),
        ("Quadratic formula", "द्विघात सूत्र"),
        ("Difference of squares", "वर्गों का अंतर"),
        ("Slope m", "ढाल m"),
        ("Distance", "दूरी"),
        ("Point–slope", "बिंदु–ढाल"),
        ("Midpoint", "मध्यबिंदु"),
        ("Trapezoid", "समलंब चतुर्भुज"),
        ("Circle sector", "वृत्त खंड"),
        ("Sphere SA", "गोले का पृष्ठीय क्षेत्रफल"),
        ("3D distance", "3D दूरी"),
        ("Rect. prism SA", "आयतनफलक का पृष्ठीय क्षेत्रफल"),
        ("Law of cosines", "कोसाइन नियम"),
        ("Law of sines", "साइन नियम"),
        ("Double angle", "द्विगुण कोण"),
        ("Arithmetic aₙ", "अंकगणितीय aₙ"),
        ("Geometric aₙ", "ज्यामितीय aₙ"),
        ("Geometric sum", "ज्यामितीय योग"),
        ("Binomial theorem", "द्विपद प्रमेय"),
        ("Mean x̄", "माध्य x̄"),
        ("σ² (population)", "σ² (जनसंख्या)"),
        ("Photosynthesis", "प्रकाश संश्लेषण"),
        ("Respiration", "श्वसन"),
        ("Rusting", "जंग"),
        ("Limewater test", "चूना जल परीक्षण"),
        ("NH₃ synthesis", "NH₃ संश्लेषण"),
        ("Benzene", "बेंजीन"),
        ("Urea", "यूरिया"),
        ("Ammonium nitrate", "अमोनियम नाइट्रेट"),
        ("Bleach", "ब्लीच"),
        ("Vinegar", "सिरका"),
        ("Chalk", "चॉक"),
        ("Gypsum", "जिप्सम"),
        ("Pen", "कलम"),
        ("Spotlight", "स्पॉटलाइट"),
        ("Timer", "टाइमर"),
        ("Presentation timer", "प्रस्तुति टाइमर"),
        ("Minutes", "मिनट"),
        ("Set", "सेट करें"),
        ("Start", "शुरू"),
        ("Pause", "विराम"),
        ("Clear highlighter", "हाइलाइटर साफ़ करें"),
        ("Style copied — select target nodes and click again to apply",
         "शैली कॉपी हुई — लक्ष्य नोड चुनें और लागू करने के लिए फिर क्लिक करें"),
        ("Format applied to {count} node(s)",
         "{count} नोड पर प्रारूप लागू"),
        ("Format painter cancelled", "फ़ॉर्मेट पेंटर रद्द"),
        ("{n} online", "{n} ऑनलाइन"),
    ]
    return apply_pairs(value, pairs)


def emit_locale(code: str, out_path: Path, mapper: Callable[[str], str]) -> None:
    nl_text = NL_PATH.read_text(encoding="utf-8")
    rows = nl_key_multiline_rows(nl_text)
    en_vals = parse_values_ordered(EN_PATH)
    if len(rows) != len(en_vals):
        raise SystemExit(f"{code}: keys {len(rows)} en {len(en_vals)}")
    mapped = [mapper(v) for v in en_vals]
    lines = [
        "/**",
        f" * {code} UI — canvas",
        " */",
        "",
        "export default {",
    ]
    for (key, multiline), val in zip(rows, mapped, strict=True):
        esc = encode_ts_single_quoted(val)
        if multiline:
            lines.append(f"  '{key}':")
            lines.append(f"    '{esc}',")
        else:
            lines.append(f"  '{key}': '{esc}',")
    lines.append("}")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    emit_locale("sq", LOCALES["sq"], to_albanian)
    emit_locale("ar", LOCALES["ar"], to_arabic)
    emit_locale("hi", LOCALES["hi"], to_hindi)
    print("Wrote sq, ar, hi canvas.ts")


if __name__ == "__main__":
    main()
