/**
 * Build pt/canvas.ts from Spanish (es) strings — replaces VALUES only.
 * Run: node scripts/rewrite-pt-canvas-from-es.ts
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import es from '../src/locales/messages/es/canvas.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = join(__dirname, '../src/locales/messages/pt/canvas.ts')

const REPS: [string, string][] = [
  ['inténtelo de nuevo', 'tente novamente'],
  [
    'No se puede exportar: el lienzo no está listo',
    'Não é possível exportar: a tela não está pronta',
  ],
  ['Error al exportar', 'Falha ao exportar'],
  [' exportado correctamente', ' exportado com sucesso'],
  ['Formato de exportación desconocido', 'Formato de exportação desconhecido'],
  [
    'Archivo de diagrama no válido. Seleccione un JSON exportado desde MindGraph.',
    'Ficheiro de diagrama inválido. Selecione um ficheiro JSON exportado do MindGraph.',
  ],
  ['No se pudo analizar el JSON', 'Não foi possível analisar o ficheiro JSON'],
  [
    '¿Seguro? Se perderá todo el contenido actual, incluido el diagrama y la paleta de nodos. No se puede deshacer.',
    'Tem a certeza? Todo o conteúdo atual será perdido, incluindo o diagrama e a paleta de nós. Esta ação não pode ser anulada.',
  ],
  ['Restablecer valores predeterminados', 'Repor valores predefinidos'],
  [
    'No se puede restablecer: elija primero un tipo de diagrama',
    'Não é possível repor: escolha primeiro um tipo de diagrama',
  ],
  ['Añadir par de analogías', 'Adicionar par de analogias'],
  ['Añadir atributo', 'Adicionar atributo'],
  ['Añadir causa', 'Adicionar causa'],
  ['Añadir efecto', 'Adicionar efeito'],
  ['Añadir nodo en desarrollo', 'Adicionar nó em desenvolvimento'],
  ['Añadir nodo', 'Adicionar nó'],
  ['Añadir subpaso', 'Adicionar subpasso'],
  ['Añadir paso', 'Adicionar passo'],
  ['Añadir par', 'Adicionar par'],
  ['Añadir', 'Adicionar'],
  ['Generar con IA', 'Gerar com IA'],
  ['Generando…', 'A gerar…'],
  ['Alinear', 'Alinhar'],
  ['Par de analogías añadido', 'Par de analogias adicionado'],
  ['Atributo añadido', 'Atributo adicionado'],
  ['Color de fondo', 'Cor de fundo'],
  ['Grosor', 'Espessura'],
  ['Rama añadida', 'Ramo adicionado'],
  ['No se puede añadir hijo', 'Não é possível adicionar filho'],
  [
    'No se puede eliminar la etiqueta de dimensión',
    'Não é possível eliminar a etiqueta de dimensão',
  ],
  ['No se puede eliminar el nodo de evento', 'Não é possível eliminar o nó de evento'],
  [
    'No se puede eliminar el/los nodo(s) seleccionado(s)',
    'Não é possível eliminar o(s) nó(s) selecionado(s)',
  ],
  ['No se puede eliminar el nodo de tema', 'Não é possível eliminar o nó de tópico'],
  ['No se puede generar', 'Não é possível gerar'],
  ['Nodo de causa añadido', 'Nó de causa adicionado'],
  ['Hijo añadido', 'Filho adicionado'],
  [
    'Solo el propietario del diagrama puede usar la generación con IA durante la colaboración',
    'Apenas o proprietário do diagrama pode usar a geração por IA durante a colaboração',
  ],
  ['Generación de conceptos', 'Geração de conceitos'],
  [
    'Los modos de mapa conceptual están en desarrollo',
    'Os modos de mapa conceptual estão em desenvolvimento',
  ],
  ['Cree primero un diagrama', 'Crie primeiro um diagrama'],
  ['Eliminar par de analogías', 'Eliminar par de analogias'],
  ['Eliminar nodos', 'Eliminar nós'],
  ['Eliminar nodo', 'Eliminar nó'],
  ['Se eliminaron {count} par(es) de analogías', 'Foram eliminados {count} par(es) de analogias'],
  ['Se eliminaron {count} atributo(s)', 'Foram eliminados {count} atributo(s)'],
  ['Se eliminaron {count} nodo(s)', 'Foram eliminados {count} nó(s)'],
  ['Diferencia A{n}', 'Diferença A{n}'],
  ['Diferencia B{n}', 'Diferença B{n}'],
  ['Par de diferencias añadido', 'Par de diferenças adicionado'],
  ['Dirección', 'Direção'],
  ['Nodo de efecto añadido', 'Nó de efeito adicionado'],
  [
    'Dibuje en el lienzo como un marcador; se borra al salir de la presentación',
    'Desenhe na tela como um marcador; é limpo ao sair da apresentação',
  ],
  ['Color del marcador', 'Cor do marcador'],
  ['Elegir color del marcador', 'Escolher cor do marcador'],
  ['Insertar ecuación', 'Inserir equação'],
  [
    'Inserte matemáticas en línea ($...$) en el cursor, o añada al nodo seleccionado si no está editando',
    'Insira matemática em linha ($...$) na posição do cursor ou adicione ao nó selecionado se não estiver a editar',
  ],
  ['Seleccione primero un nodo', 'Selecione primeiro um nó'],
  ['Cargando editor matemático…', 'A carregar o editor matemático…'],
  ['Matemáticas K-12', 'Matemática K-12'],
  ['Ecuaciones K-12', 'Equações K-12'],
  ['Básico · números y comparación', 'Básico · números e comparação'],
  ['Ýlgebra · fracciones y raíces', 'Ýlgebra · frações e raízes'],
  ['Trig · log y exp', 'Trig · log e exp'],
  ['Griego · sumas y cálculo', 'Grego · somas e cálculo'],
  ['Moléculas · estados · reacciones', 'Moléculas · estados · reações'],
  ['Iones · sales · ácidos', 'Iões · sais · ácidos'],
  ['Ýlgebra · coordenadas y recta', 'Ýlgebra · coordenadas e reta'],
  ['Geometría · área y volumen', 'Geometria · área e volume'],
  ['Trigonometría · identidades', 'Trigonometria · identidades'],
  ['Sucesiones · combinatoria · estadística', 'Sucessões · combinatória · estatística'],
  ['Compuestos y sales comunes', 'Compostos e sais comuns'],
  ['Reacciones clásicas', 'Reações clássicas'],
  ['Ýcidos · orgánicos · laboratorio', 'Ýcidos · orgânicos · laboratório'],
  ['Fórmula cuadrática', 'Fórmula quadrática'],
  ['Diferencia de cuadrados', 'Diferença de quadrados'],
  ['Pendiente m', 'Declive m'],
  ['Punto–pendiente', 'Ponto–declive'],
  ['Punto medio', 'Ponto médio'],
  ['Trapecio', 'Trapézio'],
  ['Sector circular', 'Setor circular'],
  ['Ýrea esférica', 'Ýrea da esfera'],
  ['Distancia 3D', 'Distância 3D'],
  ['Ýrea prisma rectangular', 'Ýrea do prisma retangular'],
  ['Teorema del coseno', 'Teorema do cosseno'],
  ['Teorema del seno', 'Teorema do seno'],
  ['Ýngulo doble', 'Ângulo duplo'],
  ['Suma geométrica', 'Soma geométrica'],
  ['Teorema del binomio', 'Teorema do binómio'],
  ['Media x?', 'Média x?'],
  ['?² (población)', '?² (população)'],
  ['Fotosíntesis', 'Fotossíntese'],
  ['Respiración', 'Respiração'],
  ['Oxidación del hierro', 'Oxidação do ferro'],
  ['Prueba con cal', 'Teste com cal'],
  ['Síntesis de NH?', 'Síntese de NH?'],
  ['Benceno', 'Benzeno'],
  ['Nitrato de amonio', 'Nitrato de amónio'],
  ['Lejía', 'Lixívia'],
  ['Tiza', 'Giz'],
  ['Yeso', 'Gesso'],
  ['{name} está en desarrollo', '{name} está em desenvolvimento'],
  ['Chino', 'Chinês'],
  ['Inglés', 'Inglês'],
  ['Fuente', 'Fonte'],
  [
    'Estilo copiado — seleccione nodos de destino y pulse de nuevo para aplicar',
    'Estilo copiado — selecione os nós de destino e clique novamente para aplicar',
  ],
  ['Formato aplicado a {count} nodo(s)', 'Formato aplicado a {count} nó(s)'],
  ['Copiador de formato cancelado', 'Pincel de formatação cancelado'],
  ['El copiador de formato está en desarrollo', 'O pincel de formatação está em desenvolvimento'],
  ['Seleccione primero un nodo origen', 'Selecione primeiro um nó de origem'],
  ['Copiar formato', 'Pincel de formatação'],
  ['Dirección del diseño invertida', 'Direção do esquema invertida'],
  ['Hoja de aprendizaje restaurada', 'Folha de aprendizagem restaurada'],
  ['Modo estándar por ahora; más modos pronto', 'Modo standard por agora; mais modos em breve'],
  ['Huecos aleatorios para estudiar y repasar', 'Espaços aleatórios para estudar e rever'],
  ['Cascada', 'Cascata'],
  [
    'Seleccione varios nodos en lote; haga visible el pensamiento divergente y convergente',
    'Selecione vários nós em lote; torne visível o pensamento divergente e convergente',
  ],
  ['Más aplicaciones', 'Mais aplicações'],
  ['Guarde una versión de este diagrama (máx. 10)', 'Guarde uma versão deste diagrama (máx. 10)'],
  [
    'Guarde primero el diagrama antes de tomar una instantánea',
    'Guarde primeiro o diagrama antes de tirar uma instantânea',
  ],
  [
    'No se pudo guardar la instantánea; inténtelo de nuevo',
    'Não foi possível guardar a instantânea; tente novamente',
  ],
  ['Nueva asociación', 'Nova associação'],
  ['Nuevo atributo', 'Novo atributo'],
  ['Nueva causa', 'Nova causa'],
  ['Nuevo hijo', 'Novo filho'],
  ['Nuevo efecto', 'Novo efeito'],
  ['Nuevo elemento A', 'Novo elemento A'],
  ['Nuevo elemento B', 'Novo elemento B'],
  ['Nueva parte', 'Nova parte'],
  ['Nuevo paso', 'Novo passo'],
  ['Nueva subparte', 'Nova subparte'],
  ['Nuevo subpaso', 'Novo subpasso'],
  ['Nodo añadido', 'Nó adicionado'],
  ['Preajustes', 'Predefinições'],
  ['Rehacer', 'Refazer'],
  ['Seleccione una rama o un nodo hijo', 'Selecione um ramo ou um nó filho'],
  [
    'Seleccione nodos de categoría u hoja (el nodo de tema no se puede eliminar)',
    'Selecione nós de categoria ou folha (o nó de tópico não pode ser eliminado)',
  ],
  ['Seleccione primero uno o varios nodos', 'Selecione primeiro um ou vários nós'],
  ['Seleccione los nodos a eliminar', 'Selecione os nós a eliminar'],
  [
    'Seleccione una parte a la que añadir subparte',
    'Selecione uma parte à qual adicionar subparte',
  ],
  [
    'Seleccione un nodo de parte y pulse Intro para añadir subparte',
    'Selecione um nó de parte e prima Enter para adicionar subparte',
  ],
  [
    'Seleccione nodos de similitud o diferencia (los nodos de tema no se pueden eliminar)',
    'Selecione nós de semelhança ou diferença (os nós de tópico não podem ser eliminados)',
  ],
  [
    'Seleccione primero un nodo de similitud o diferencia',
    'Selecione primeiro um nó de semelhança ou diferença',
  ],
  ['Seleccione un paso al que añadir subpaso', 'Selecione um passo ao qual adicionar subpasso'],
  ['Similitud {n}', 'Semelhança {n}'],
  ['Paso añadido', 'Passo adicionado'],
  ['Corporativo', 'Profissional'],
  ['Sencillo', 'Simples'],
  ['Subparte añadida', 'Subparte adicionada'],
  ['Subpaso añadido', 'Subpasso adicionado'],
  ['Subpaso {n}.1', 'Subpasso {n}.1'],
  ['Subpaso {n}.2', 'Subpasso {n}.2'],
  ['Cambiado a modo hoja de aprendizaje', 'Mudou para modo folha de aprendizagem'],
  ['Vuelta al modo normal', 'Voltou ao modo normal'],
  ['Cambiar dirección', 'Alternar direção'],
  ['Deshacer', 'Desfazer'],
  ['Actualizar fondo', 'Atualizar fundo'],
  ['Actualizar borde', 'Atualizar contorno'],
  ['Actualizar estilo de texto', 'Atualizar estilo de texto'],
  ['Estructura alámbrica', 'Vista de arame'],
  ['Pulse para guardar', 'Clique para guardar'],
  ['Pulse para gestionar el espacio de la galería', 'Clique para gerir o espaço da galeria'],
  ['Atrás', 'Voltar'],
  ['Colaborar (escuela o compartido)', 'Colaborar (escola ou partilhado)'],
  ['Pulse para editar el nombre del archivo', 'Clique para editar o nome do ficheiro'],
  ['Restablecer plantilla predeterminada', 'Repor modelo predefinido'],
  ['Compartir en la comunidad', 'Partilhar na comunidade'],
  [
    '¿Restaurar la instantánea {n}? Los cambios actuales se sustituirán.',
    'Restaurar a instantânea {n}? As alterações atuais serão substituídas.',
  ],
  ['Antes de restaurar la instantánea {n}', 'Antes de restaurar a instantânea {n}'],
  [
    'No se pudo restaurar la instantánea; inténtelo de nuevo',
    'Não foi possível restaurar a instantânea; tente novamente',
  ],
  ['Instantánea {n} eliminada', 'Instantânea {n} eliminada'],
  [
    'No se pudo eliminar la instantánea; inténtelo de nuevo',
    'Não foi possível eliminar a instantânea; tente novamente',
  ],
  [
    'Pulse para restaurar la instantánea {n} · Ctrl+Clic para eliminar',
    'Clique para restaurar a instantânea {n} · Ctrl+clique para eliminar',
  ],
  ['Ajustar al lienzo', 'Ajustar à tela'],
  ['Pantalla completa', 'Ecrã inteiro'],
  ['Mostrar herramientas de presentación', 'Mostrar ferramentas de apresentação'],
  ['Ocultar herramientas de presentación', 'Ocultar ferramentas de apresentação'],
  ['Herramientas de presentación', 'Ferramentas de apresentação'],
  ['Puntero láser', 'Ponteiro laser'],
  ['Bolígrafo', 'Caneta'],
  ['Temporizador de presentación', 'Temporizador de apresentação'],
  ['Establecer', 'Definir'],
  ['Reiniciar', 'Repor'],
  ['Borrar marcador', 'Limpar marcador'],
  ['Salir de la presentación', 'Sair da apresentação'],
  ['Sin resultado', 'Sem resultado'],
  ['Falló la solicitud de validación', 'O pedido de validação falhou'],
  [
    'Otras posibles dimensiones de descomposición para este tema:',
    'Outras possíveis dimensões de decomposição para este tópico:',
  ],
  [
    'Otros posibles patrones de analogía para este tema:',
    'Outros possíveis padrões de analogia para este tópico:',
  ],
  [
    'Otras posibles dimensiones de clasificación para este tema:',
    'Outras possíveis dimensões de classificação para este tópico:',
  ],
  ['[Las alternativas aparecerán aquí]', '[As alternativas aparecerão aqui]'],
  ['Pregunta focal: ', 'Pergunta de foco: '],
  ['Concepto raíz', 'Conceito raiz'],
  ['concepto raíz', 'conceito raiz'],
  ['Añadir a este grupo', 'Adicionar a este grupo'],
  ['Añadir concepto', 'Adicionar conceito'],
  ['Nueva idea', 'Nova ideia'],
  [
    'La función de añadir nodo llegará pronto',
    'A função de adicionar nó estará disponível em breve',
  ],
  ['Cree primero un diagrama', 'Crie primeiro um diagrama'],
  ['Nuevo concepto', 'Novo conceito'],
  ['Clasificación por', 'Classificação por'],
  ['Descomposición por', 'Decomposição por'],
  ['Introduzca texto…', 'Introduza texto…'],
  ['Nueva causa', 'Nova causa'],
  ['Nuevo efecto', 'Novo efeito'],
  ['Relación de analogía:', 'Relação de analogia:'],
  ['pulse para indicar…', 'clique para indicar…'],
  ['[Pulse para definir]', '[Clique para definir]'],
  ['Respuestas:', 'Respostas:'],
  ['Nuevo izquierda', 'Novo à esquerda'],
  ['Nuevo derecha', 'Novo à direita'],
  ['Nueva categoría', 'Nova categoria'],
  ['Nuevo contexto', 'Novo contexto'],
  ['Nuevo elemento', 'Novo elemento'],
  ['Diferencia izquierda', 'Diferença à esquerda'],
  ['Diferencia derecha', 'Diferença à direita'],
  ['Nueva similitud', 'Nova semelhança'],
  ['Subelemento', 'Subitem'],
  ['se relaciona con', 'relaciona-se com'],
  ['Categoría {n}', 'Categoria {n}'],
  ['Tema central', 'Tópico central'],
  ['Hijo {n}.{m}', 'Filho {n}.{m}'],
  ['Efecto {n}', 'Efeito {n}'],
  ['Tema raíz', 'Tópico raiz'],
  ['Paso {n}', 'Passo {n}'],
  ['Subpaso {n}.{m}', 'Subpasso {n}.{m}'],
  ['Tema', 'Tópico'],
  ['Pulse 1–5 para seleccionar', 'Prima 1–5 para selecionar'],
  ['Relación', 'Relação'],
  ['Introduzca la relación…', 'Introduza a relação…'],
  ['Guardado a las {time}', 'Guardado às {time}'],
  ['Guardado hace un momento', 'Guardado há um momento'],
  ['Guardado hace {n} s', 'Guardado há {n} s'],
  ['Guardado hace {n} min', 'Guardado há {n} min'],
  ['Guardando…', 'A guardar…'],
  ['Cambios sin guardar', 'Alterações não guardadas'],
  ['Inicie sesión para guardar', 'Inicie sessão para guardar'],
  ['Exportar imagen', 'Exportar imagem'],
  ['Ajustar a la pantalla', 'Ajustar ao ecrã'],
  ['Nuevo diagrama', 'Novo diagrama'],
  ['Guardar diagrama', 'Guardar diagrama'],
  ['Seleccionar tipo de diagrama', 'Selecionar tipo de diagrama'],
  [
    'Espacio lleno; el autoguardado no está disponible ahora. Elimine diagramas para liberar espacio.',
    'Espaço cheio; a gravação automática não está disponível de momento. Elimine diagramas para libertar espaço.',
  ],
  ['Nueva subparte 1', 'Nova subparte 1'],
  ['Nueva subparte 2', 'Nova subparte 2'],
  ['No hay datos del diagrama para exportar', 'Não há dados do diagrama para exportar'],
  [
    'Formato de código de presentación no válido (debe ser xxx-xxx)',
    'Formato do código de apresentação inválido (deve ser xxx-xxx)',
  ],
  ['Introduzca el código de presentación completo', 'Introduza o código de apresentação completo'],
  ['No se pudo unir', 'Não foi possível entrar'],
  ['No se pudo unir a la presentación', 'Não foi possível entrar na apresentação'],
  ['Unido: {title}', 'Entrou: {title}'],
  ['Presentación unida: {title}', 'Apresentação: {title}'],
  [
    'No se pudieron cargar las sesiones escolares',
    'Não foi possível carregar as sessões escolares',
  ],
  ['Error de red; no se pudo unir', 'Erro de rede; não foi possível entrar'],
  [
    'No hay sesiones escolares ahora. Un colega debe iniciar «Colaboración escolar» en el lienzo.',
    'Não há sessões escolares neste momento. Um colega deve iniciar «Colaboração escolar» na tela.',
  ],
  ['{n} en línea', '{n} em linha'],
  [
    'Introduzca el código de invitación (xxx-xxx) para unirse a su sesión.',
    'Introduza o código de convite (xxx-xxx) para entrar na sessão.',
  ],
  [
    'Hola {username}, soy tu asistente de pensamiento visual con IA',
    'Olá {username}, sou o seu assistente de pensamento visual com IA',
  ],
]

function spToPt(s: string): string {
  let out = s
  const ordered = [...REPS].sort((a, b) => b[0].length - a[0].length)
  for (const [from, to] of ordered) {
    out = out.split(from).join(to)
  }
  return out
}

function main(): void {
  const flat = es as Record<string, string>
  const lines: string[] = [
    '/** pt UI — canvas (Brazilian/European neutral UI Portuguese) */',
    'export default {',
  ]
  for (const key of Object.keys(flat)) {
    lines.push(`  ${JSON.stringify(key)}: ${JSON.stringify(spToPt(flat[key]))},`)
  }
  lines.push('} as const', '')
  writeFileSync(OUT, lines.join('\n'), 'utf8')
}

main()
