/**
 * Language Composable - i18n switching
 * Migrated from language-manager.js
 */
import { computed } from 'vue'

import { type Language, useUIStore } from '@/stores/ui'

// Translation dictionaries - exported for use in stores
export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.loading': 'Loading...',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.warning': 'Warning',
    'common.refresh': 'Refresh',

    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.logout': 'Logout',
    'auth.username': 'Username',
    'auth.phone': 'Phone Number',
    'auth.password': 'Password',
    'auth.captcha': 'Captcha',
    'auth.enterCaptcha': 'Enter captcha',
    'auth.clickToRefresh': 'Click image to refresh',
    'auth.loginFailed': 'Login failed',
    'auth.sessionExpired': 'Session expired. Please login again.',
    'auth.smsLogin': 'SMS Login',
    'auth.resetPassword': 'Reset Password',
    'auth.backToLogin': 'Back to Login',

    // Editor
    'editor.newDiagram': 'New Diagram',
    'editor.saveDiagram': 'Save Diagram',
    'editor.exportImage': 'Export Image',
    'editor.undo': 'Undo',
    'editor.redo': 'Redo',
    'editor.zoomIn': 'Zoom In',
    'editor.zoomOut': 'Zoom Out',
    'editor.fitToScreen': 'Fit to Screen',
    'editor.selectDiagramType': 'Select Diagram Type',
    'editor.autoSavedAt': 'Auto-saved at {time}',
    'editor.clickToSave': 'Click to save',
    'editor.slotsFull':
      'Space full, auto-save not available at the moment. Please delete existing diagrams to free more space.',

    // Diagram nodes (matching old JS languageManager)
    'diagram.newAttribute': 'New Attribute',
    'diagram.newBranch': 'New Branch',
    'diagram.newSubitem': 'Sub-item',
    'diagram.newStep': 'New Step',
    'diagram.newSubstep': 'New Substep',
    'diagram.newPart': 'New Part',
    'diagram.newChild': 'New Child',
    'diagram.relationshipPlaceholder': 'Enter relationship...',
    'diagram.aiGenerating': 'AI...',
    'diagram.relationship': 'Relationship',
    'diagram.pressNumberToSelect': 'Press 1–5 to select',

    // Panels
    'panel.mindmate': 'MindMate AI',
    'panel.nodePalette': 'Node Palette',
    'panel.properties': 'Properties',

    // AskOnce
    'askonce.title': 'AskOnce',

    // Admin
    'admin.title': 'Admin Panel',
    'admin.orgManagement': 'Organization Management',
    'admin.dashboard': 'Dashboard',
    'admin.users': 'Users',
    'admin.schools': 'Schools',
    'admin.roleControl': 'Role Control',
    'admin.roleControlDesc': 'Manage admin access. Users with admin role can access the management panel.',
    'admin.adminsTab': 'Admins',
    'admin.schoolManagersTab': 'School Managers',
    'admin.roleControlDescManagers': 'Manage school managers. Managers can access the school dashboard for their organization.',
    'admin.noManagersFound': 'No school managers',
    'admin.managerRoleRemoved': 'Manager role removed',
    'admin.addAdmin': 'Add Admin',
    'admin.revokeAdmin': 'Revoke Admin',
    'admin.revokeAdminConfirm': 'Revoke admin access from',
    'admin.grantAdmin': 'Grant Admin',
    'admin.adminRoleGranted': 'Admin role granted',
    'admin.adminRoleRevoked': 'Admin role revoked',
    'admin.envAdmins': 'Environment-configured Admins',
    'admin.envAdminsNote': 'Configured via ADMIN_PHONES in .env (read-only)',
    'admin.source': 'Source',
    'admin.sourceEnv': 'Env (.env)',
    'admin.sourceDatabase': 'Database',
    'admin.searchUserByNameOrPhone': 'Search by name or phone',
    'admin.noUsersFound': 'No users found',
    'admin.confirm': 'Confirm',
    'admin.schoolDashboard': 'School Dashboard',
    'admin.viewSchool': 'View school',
    'admin.selectSchool': 'Select school',
    'admin.schoolDashboardNoOrg': 'You must belong to a school to view the dashboard.',
    'admin.topUsersByTokens': 'Top Users by Token Usage',
    'admin.managers': 'Managers',
    'admin.setManager': 'Set as Manager',
    'admin.removeManager': 'Remove Manager',
    'admin.refreshInvitationCode': 'Refresh Invitation Code',
    'admin.invitationCode': 'Invitation Code',
    'admin.tokens': 'Token Usage',
    'admin.apiKeys': 'API Keys',
    'admin.geweWechat': 'Gewe WeChat',
    'admin.logs': 'Logs',
    'admin.announcements': 'Announcements',
    'admin.totalUsers': 'Total Users',
    'admin.activeToday': 'Active Today',
    'admin.totalDiagrams': 'Total Diagrams',
    'admin.apiCalls': 'API Calls',
    'admin.userActivity': 'User Activity',
    'admin.viewAll': 'View All',
    'admin.chartPlaceholderUserActivity': 'Chart placeholder - User activity over time',
    'admin.diagramTypes': 'Diagram Types',
    'admin.chartPlaceholderDiagramTypes': 'Chart placeholder - Diagram type distribution',
    'admin.userManagement': 'User Management',
    'admin.addUser': 'Add User',
    'admin.userManagementPlaceholder': 'User management interface will be implemented here',
    'admin.loadingTokenStats': 'Loading token statistics...',
    'admin.tokenUsageByService': 'Token Usage by Service',
    'admin.tokenUsageCompare':
      'Compare token usage between MindGraph (diagrams) and MindMate (AI assistant)',
    'admin.diagramGeneration': 'Diagram Generation',
    'admin.aiAssistant': 'AI Assistant (Dify)',
    'admin.today': 'Today',
    'admin.thisWeek': 'This Week',
    'admin.thisMonth': 'This Month',
    'admin.allTime': 'All Time',
    'admin.requests': 'requests',
    'admin.inputTokens': 'Input Tokens (All Time)',
    'admin.outputTokens': 'Output Tokens (All Time)',
    'admin.overallTokenSummary': 'Overall Token Usage Summary',
    'admin.pastWeek': 'Past Week',
    'admin.pastMonth': 'Past Month',
    'admin.noTokenStats': 'No token statistics available',
    'admin.loadStatistics': 'Load Statistics',
    'admin.inShort': 'In',
    'admin.outShort': 'Out',
    'admin.dashboardLoadError': 'Network error, failed to load dashboard stats',
    'admin.tokenStatsLoadError': 'Failed to load token stats',
    'admin.tokenStatsNetworkError': 'Network error, failed to load token stats',
    'admin.managementInterface': 'management interface',
    'admin.todayRegistrations': "Today's Registrations",
    'admin.topSchoolsByTokens': 'Top Schools by Token Usage',
    'admin.schoolName': 'School Name',
    'admin.schoolCode': 'School Code',
    'admin.schoolCodeAutoGenerated': 'Auto-generated from school name',
    'admin.regenerateSchoolCode': 'Regenerate school code',
    'admin.invitationCodeAutoGenerated':
      'Invitation code will be automatically generated after creation.',
    'admin.schoolNameRequired': 'School name is required',
    'admin.schoolCodeRequired': 'School code could not be generated from name. Please enter a code.',
    'admin.search': 'Search',
    'admin.reset': 'Reset',
    'admin.actions': 'Actions',
    'admin.createSchool': 'Create School',
    'admin.editSchool': 'Edit School',
    'admin.createApiKey': 'Create API Key',
    'admin.editApiKey': 'Edit API Key',
    'admin.name': 'Name',
    'admin.phone': 'Phone',
    'admin.organization': 'Organization',
    'admin.tokensUsed': 'Tokens Used',
    'admin.registrationTime': 'Registration Time',
    'admin.status': 'Status',
    'admin.usersCount': 'Users',
    'admin.apiKey': 'API Key',
    'admin.usage': 'Usage',
    'admin.created': 'Created',
    'admin.lastUsed': 'Last Used',
    'admin.enabled': 'Enabled',
    'admin.disabled': 'Disabled',
    'admin.save': 'Save',
    'admin.cancel': 'Cancel',
    'admin.delete': 'Delete',
    'admin.refresh': 'Refresh',
    'admin.filterBySchool': 'Filter by School',
    'admin.allSchools': 'All Schools',
    'admin.previous': 'Previous',
    'admin.next': 'Next',
    'admin.noData': 'No data',
    'admin.loading': 'Loading...',
    'admin.description': 'Description',
    'admin.shareInviteTitle': 'Share Invitation',
    'admin.copyShareMessage': 'Copy',
    'admin.shareInviteMessage':
      'Dear School Administrator, we cordially invite you and your school team to experience MindGraph — our AI-powered mind map generation software, dedicated to developing teaching information platforms. Your school\'s exclusive invitation code is: {code} Please visit mg.mingspringedu.com to complete registration and begin efficient, intuitive visual collaboration. We look forward to contributing to your school\'s educational innovation.',
    'admin.trendChart': 'Trend Chart',
    'admin.trendUsers': 'Total Users Trend',
    'admin.trendOrganizations': 'Organizations Trend',
    'admin.trendRegistrations': 'Daily Registrations Trend',
    'admin.trendTokens': 'Token Usage Trend',
    'admin.trendOrgTokens': 'Token Usage by School',
    'admin.trendUserTokens': 'Token Usage by User',
    'admin.displayNameLabel': 'Sidebar Display Text',
    'admin.displayNameHint': 'Custom text shown in user sidebar (e.g. MindGraph Pro). Leave empty to use school name.',
    'admin.lockOrganization': 'Lock Organization',
    'admin.unlockOrganization': 'Unlock Organization',
    'admin.deleteOrganization': 'Delete Organization',
    'admin.deleteOrgConfirm': 'Delete organization {name}? This cannot be undone.',
    'admin.deleteOrgConfirmWithUsers':
      'Delete organization {name} and all {count} user accounts? This cannot be undone.',
    'admin.dangerZone': 'Danger Zone',
    'admin.expirationDate': 'Expiration Date',
    'admin.expirationDateHint':
      'Organization will be locked after this date. Leave empty for no limit.',
    'admin.noExpiration': 'No expiration',

    // Library admin tab
    'admin.library': 'Library',
    'admin.library.tabTitle': 'Library Management',
    'admin.library.tabSubtitle': 'Scan, register, and manage image book folders',
    'admin.library.scan': 'Scan',
    'admin.library.scanning': 'Scanning storage folder...',
    'admin.library.registerAll': 'Register All New',
    'admin.library.register': 'Register',
    'admin.library.reRegister': 'Re-register',
    'admin.library.lastScanned': 'Last scanned',
    'admin.library.totalFolders': 'Total Folders',
    'admin.library.registered': 'Registered',
    'admin.library.visible': 'Visible',
    'admin.library.newUnregistered': 'New',
    'admin.library.colTitle': 'Book / Folder',
    'admin.library.colPages': 'Pages',
    'admin.library.colStatus': 'Status',
    'admin.library.colVisible': 'Visible',
    'admin.library.colActions': 'Actions',
    'admin.library.statusNew': 'New',
    'admin.library.statusRegistered': 'Registered',
    'admin.library.statusRepair': 'Needs Repair',
    'admin.library.statusOrphaned': 'Orphaned',
    'admin.library.diskPresent': 'Folder exists on disk',
    'admin.library.diskMissing': 'Folder not found on disk',
    'admin.library.storageDir': 'Storage path',
    'admin.library.noFolders': 'No image folders found in storage/library/',
    'admin.library.scanError': 'Failed to scan library storage',
    'admin.library.registerSuccess': 'Book registered successfully',
    'admin.library.registerAllSuccess': 'Registered',
    'admin.library.registerError': 'Failed to register book',
    'admin.library.visibilityError': 'Failed to update visibility',
    'admin.library.renamePages': 'Rename Pages',
    'admin.library.renameDialogTitle': 'Rename Page Files',
    'admin.library.renameBookNameLabel': 'Book name prefix',
    'admin.library.renameBookNameHint': 'Files will be renamed to',
    'admin.library.renamePreview': 'Preview',
    'admin.library.renamePreviewLoading': 'Building rename plan...',
    'admin.library.renameColFrom': 'Current Name',
    'admin.library.renameColTo': 'New Name',
    'admin.library.renameFilesToRename': 'files to rename',
    'admin.library.renameFilesAlreadyOk': 'already correct',
    'admin.library.renameNoChanges': 'All files are already correctly named',
    'admin.library.renameApply': 'Apply Rename',
    'admin.library.renameSuccess': 'Successfully renamed {count} files',
    'admin.library.renameError': 'Rename failed',
    'admin.library.generateCover': 'Generate Cover',
    'admin.library.generateCoverSuccess': 'Cover generated successfully',
    'admin.library.generateCoverError': 'Failed to generate cover',
    'admin.library.deleteBook': 'Delete Book',
    'admin.library.deleteBookTitle': 'Delete Book',
    'admin.library.deleteBookConfirmMsg': 'Permanently delete all {count} page images from disk AND the database record for "{name}"? This cannot be undone.',
    'admin.library.deleteBookConfirm': 'Yes, delete everything',
    'admin.library.deleteBookSuccess': 'Book deleted',
    'admin.library.deleteRecord': 'Delete Record',
    'admin.library.deleteConfirmTitle': 'Delete Document Record',
    'admin.library.deleteConfirmMsg': 'Permanently delete the database record for "{name}"? Page images on disk are not affected.',
    'admin.library.deleteSuccess': 'Record deleted',
    'admin.library.deleteError': 'Failed to delete',

    // Workshop Chat
    'workshop.title': 'Workshop',
    'workshop.channels': 'Channels',
    'workshop.dms': 'DMs',
    'workshop.directMessages': 'Direct Messages',
    'workshop.conversations': 'Conversations',
    'workshop.generalChat': 'General Chat',
    'workshop.topics': 'Conversations',
    'workshop.recentTopics': 'Recent Conversations',
    'workshop.newTopic': 'New Conversation',
    'workshop.noTopicsYet': 'No conversations yet',
    'workshop.showAllTopics': 'Show all conversations',
    'workshop.more': 'more',
    'workshop.createStudyCaseHint': 'Start a conversation to get started',
    'workshop.noConversationsYet': 'No conversations yet',
    'workshop.selectConversation': 'Select a conversation',
    'workshop.noChannelsJoined': 'No channels joined',
    'workshop.noChannelsAvailable': 'No channels available',
    'workshop.noMessagesYet': 'No messages yet',
    'workshop.startConversation': 'Start the conversation!',
    'workshop.members': 'members',
    'workshop.topicCount': 'conversations',
    'workshop.join': 'Join',
    'workshop.leave': 'Leave',
    'workshop.create': 'Create',
    'workshop.viewDiagram': 'View Diagram',
    'workshop.diagram': 'Diagram',
    'workshop.by': 'by',
    'workshop.unknown': 'Unknown',
    'workshop.edited': '(edited)',
    'workshop.messageDeleted': 'This message was deleted',
    'workshop.newMessage': 'New message...',
    'workshop.typeMessagePlaceholder': 'Type a message... (Enter to send, Shift+Enter for new line)',
    'workshop.topicTitle': 'Title',
    'workshop.topicTitlePlaceholder': 'e.g. Design thinking map for Chapter 3',
    'workshop.topicDescription': 'Description',
    'workshop.topicDescriptionPlaceholder': 'Describe the conversation topic...',
    'workshop.conversationTitle': 'Conversation Title',
    'workshop.conversationTitlePlaceholder': 'e.g. Lesson plan discussion, Teaching reflection',
    'workshop.startConversationHint': 'Start a conversation to discuss with your colleagues',
    'workshop.view': 'View',
    'workshop.dismiss': 'Dismiss',
    'workshop.statusOpen': 'Open',
    'workshop.statusInProgress': 'In Progress',
    'workshop.statusCompleted': 'Completed',
    'workshop.statusArchived': 'Archived',
    'workshop.mentionedInChannel': 'You were mentioned in #{0}',
    'workshop.mentionedInTopic': 'You were mentioned in {0}',
    'workshop.directMessage': 'Direct Message',
    'workshop.contacts': 'Contacts',
    'workshop.startDM': 'Send Message',
    'workshop.noMembersFound': 'No members found',
    'workshop.searchMembers': 'Search members...',
    'workshop.switchSchool': 'Switch School',
    'workshop.allSchools': 'All Schools',
    'workshop.viewingSchool': 'Viewing: {0}',
    'workshop.mySchool': 'My School',
    'workshop.showMore': 'Show more',
    'workshop.showLess': 'Show less',
    'workshop.addReaction': 'Add reaction',
    'workshop.starMessage': 'Star message',
    'workshop.unstarMessage': 'Unstar message',
    'workshop.quoteMessage': 'Quote message',
    'workshop.copyLink': 'Copy link',
    'workshop.uploadFile': 'Upload file',
    'workshop.download': 'Download',
    'workshop.linkCopied': 'Link copied',
    'workshop.bold': 'Bold',
    'workshop.italic': 'Italic',
    'workshop.code': 'Code',
    'workshop.codeBlock': 'Code block',
    'workshop.strikethrough': 'Strikethrough',
    'workshop.insertLink': 'Insert link',
    'workshop.emoji': 'Emoji',
    'workshop.moreActions': 'More actions',
    'workshop.searchMessages': 'Search messages...',
    'workshop.newConversation': 'New conversation',
    'workshop.selectTopic': 'Select conversation',
    'workshop.youAnd': 'You and',
    'workshop.online': 'online',
    'workshop.offline': 'offline',
    'workshop.filterUsers': 'Filter users',
    'workshop.filterSidebar': 'Filter channels, DMs',
    'workshop.views': 'Views',
    'workshop.inbox': 'Inbox',
    'workshop.starred': 'Starred',
    'workshop.mentions': 'Mentions',
    'workshop.browseChannels': 'Browse channels',
    'workshop.newDM': 'New direct message',
    'workshop.composeMessage': 'Compose message',
    'workshop.composeMessageTo': 'Message',
    'workshop.startNewConversation': 'Start new conversation',
    'workshop.newDirectMessage': 'New direct message',
    'workshop.noMembers': 'No members',
    'workshop.thisConversation': 'THIS CONVERSATION',
    'workshop.thisChannel': 'THIS CHANNEL',
    'workshop.others': 'OTHERS',
    'workshop.viewAllMembers': 'View all members',
    'workshop.you': '(you)',
    'workshop.announceChannels': 'Announcements',
    'workshop.publicChannels': 'Public Channels',
    'workshop.privateChannels': 'Private Channels',
    'workshop.channelSettings': 'Channel Settings',
    'workshop.channelType': 'Channel Type',
    'workshop.channelTypeAnnounce': 'Announce',
    'workshop.channelTypePublic': 'Public',
    'workshop.channelTypePrivate': 'Private',
    'workshop.postingPolicy': 'Posting Policy',
    'workshop.policyEveryone': 'Everyone',
    'workshop.policyManagers': 'Managers only',
    'workshop.policyMembersOnly': 'Members only',
    'workshop.defaultChannel': 'Default channel',
    'workshop.muteChannel': 'Mute channel',
    'workshop.unmuteChannel': 'Unmute channel',
    'workshop.pinChannel': 'Pin to top',
    'workshop.unpinChannel': 'Unpin',
    'workshop.channelColor': 'Channel color',
    'workshop.notifications': 'Notifications',
    'workshop.desktopNotifications': 'Desktop notifications',
    'workshop.emailNotifications': 'Email notifications',
    'workshop.topicSettings': 'Conversation Settings',
    'workshop.moveTopic': 'Move to channel',
    'workshop.renameTopic': 'Rename conversation',
    'workshop.deleteTopic': 'Delete conversation',
    'workshop.deleteTopicConfirm': 'Are you sure you want to delete this conversation?',
    'workshop.markAsRead': 'Mark as read',
    'workshop.muteTopic': 'Mute conversation',
    'workshop.unmuteTopic': 'Unmute conversation',
    'workshop.followTopic': 'Follow conversation',
    'workshop.unfollowTopic': 'Unfollow conversation',
    'workshop.permissions': 'Permissions',
    'workshop.gearMenu': 'Settings',
    'workshop.personalMenu': 'Personal Menu',
    'workshop.toggleContacts': 'Toggle contacts',
    'workshop.profile': 'Profile',
    'workshop.preferences': 'Preferences',
    'workshop.signOut': 'Sign Out',
    'workshop.viewProfile': 'View profile',
    'workshop.sendDirectMessage': 'Send direct message',
    'workshop.replyMentioning': 'Reply mentioning user',
    'workshop.copyMentionSyntax': 'Copy mention syntax',
    'workshop.manageUser': 'Manage this user',
    'workshop.presenceActive': 'Active',
    'workshop.presenceIdle': 'Idle',
    'workshop.presenceOffline': 'Offline',
    'workshop.roleAdmin': 'Admin',
    'workshop.roleManager': 'Manager',
    'workshop.roleOwner': 'Owner',

    // Notifications
    'notification.saved': 'Changes saved successfully',
    'notification.copied': 'Copied to clipboard',
    'notification.copyFailed': 'Failed to copy',
    'notification.deleted': 'Item deleted successfully',
    'notification.sessionInvalidated':
      'You have been logged out because you exceeded the maximum number of devices',
    'notification.newVersionAvailable': 'New version available. Click to refresh.',
  },
  zh: {
    // Common
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.confirm': '确认',
    'common.close': '关闭',
    'common.loading': '加载中...',
    'common.success': '成功',
    'common.error': '错误',
    'common.warning': '警告',
    'common.refresh': '刷新',

    // Auth
    'auth.login': '登录',
    'auth.register': '注册',
    'auth.logout': '退出登录',
    'auth.username': '用户名',
    'auth.phone': '手机号',
    'auth.password': '密码',
    'auth.captcha': '验证码',
    'auth.enterCaptcha': '请输入验证码',
    'auth.clickToRefresh': '点击图片刷新验证码',
    'auth.loginFailed': '登录失败',
    'auth.sessionExpired': '会话已过期，请重新登录。',
    'auth.smsLogin': '短信登录',
    'auth.resetPassword': '重置密码',
    'auth.backToLogin': '返回登录',
    'auth.forgotPassword': '忘记密码',

    // Editor
    'editor.newDiagram': '新建图表',
    'editor.saveDiagram': '保存图表',
    'editor.exportImage': '导出图片',
    'editor.undo': '撤销',
    'editor.redo': '重做',
    'editor.zoomIn': '放大',
    'editor.zoomOut': '缩小',
    'editor.fitToScreen': '适应屏幕',
    'editor.selectDiagramType': '选择图表类型',
    'editor.autoSavedAt': '已自动保存 {time}',
    'editor.clickToSave': '点击保存',
    'editor.slotsFull': '空间已满，暂无法自动保存。请删除现有图示以释放空间。',

    // Diagram nodes (matching old JS languageManager)
    'diagram.newAttribute': '新属性',
    'diagram.newBranch': '新分支',
    'diagram.newSubitem': '子项',
    'diagram.newStep': '新步骤',
    'diagram.newSubstep': '新子步骤',
    'diagram.newPart': '新部分',
    'diagram.newChild': '新子项',
    'diagram.relationshipPlaceholder': '输入关系...',
    'diagram.aiGenerating': 'AI...',
    'diagram.relationship': '关系',
    'diagram.pressNumberToSelect': '按 1–5 选择',

    // Panels
    'panel.mindmate': 'MindMate AI 助手',
    'panel.nodePalette': '节点面板',
    'panel.properties': '属性',

    // AskOnce
    'askonce.title': '多应',

    // Admin
    'admin.title': '管理面板',
    'admin.orgManagement': '组织管理',
    'admin.dashboard': '仪表盘',
    'admin.users': '用户',
    'admin.schools': '学校',
    'admin.roleControl': '角色控制',
    'admin.roleControlDesc': '管理管理员权限。拥有管理员角色的用户可访问管理面板。',
    'admin.adminsTab': '管理员',
    'admin.schoolManagersTab': '学校管理员',
    'admin.roleControlDescManagers': '管理学校管理员。学校管理员可访问其所属组织的学校仪表盘。',
    'admin.noManagersFound': '暂无学校管理员',
    'admin.managerRoleRemoved': '已移除学校管理员权限',
    'admin.addAdmin': '添加管理员',
    'admin.revokeAdmin': '移除管理员',
    'admin.revokeAdminConfirm': '确定要移除以下用户的管理员权限：',
    'admin.grantAdmin': '授予管理员',
    'admin.adminRoleGranted': '已授予管理员权限',
    'admin.adminRoleRevoked': '已移除管理员权限',
    'admin.envAdmins': '环境变量配置的管理员',
    'admin.envAdminsNote': '通过 .env 中的 ADMIN_PHONES 配置（只读）',
    'admin.source': '来源',
    'admin.sourceEnv': '环境变量 (.env)',
    'admin.sourceDatabase': '数据库',
    'admin.searchUserByNameOrPhone': '按姓名或手机号搜索',
    'admin.noUsersFound': '未找到用户',
    'admin.confirm': '确定',
    'admin.schoolDashboard': '学校仪表盘',
    'admin.viewSchool': '查看学校',
    'admin.selectSchool': '选择学校',
    'admin.schoolDashboardNoOrg': '您需要属于某个学校才能查看仪表盘。',
    'admin.topUsersByTokens': '用户 Token 使用排行',
    'admin.managers': '管理员',
    'admin.setManager': '设为管理员',
    'admin.removeManager': '移除管理员',
    'admin.refreshInvitationCode': '刷新邀请码',
    'admin.invitationCode': '邀请码',
    'admin.tokens': 'Token使用量',
    'admin.apiKeys': 'API 密钥',
    'admin.geweWechat': 'Gewe 微信',
    'admin.logs': '日志',
    'admin.announcements': '公告',
    'admin.totalUsers': '总用户数',
    'admin.activeToday': '今日活跃',
    'admin.totalDiagrams': '总图表数',
    'admin.apiCalls': 'API 调用',
    'admin.userActivity': '用户活跃度',
    'admin.viewAll': '查看全部',
    'admin.chartPlaceholderUserActivity': '图表占位 - 用户活跃度随时间变化',
    'admin.diagramTypes': '图表类型',
    'admin.chartPlaceholderDiagramTypes': '图表占位 - 图表类型分布',
    'admin.userManagement': '用户管理',
    'admin.addUser': '添加用户',
    'admin.userManagementPlaceholder': '用户管理界面将在此实现',
    'admin.loadingTokenStats': '正在加载 Token 统计...',
    'admin.tokenUsageByService': '按服务统计 Token 使用量',
    'admin.tokenUsageCompare': '对比 MindGraph（图表）与 MindMate（AI 助手）的 Token 使用',
    'admin.diagramGeneration': '图表生成',
    'admin.aiAssistant': 'AI 助手 (Dify)',
    'admin.today': '今日',
    'admin.thisWeek': '本周',
    'admin.thisMonth': '本月',
    'admin.allTime': '全部',
    'admin.requests': '次请求',
    'admin.inputTokens': '输入 Token（全部）',
    'admin.outputTokens': '输出 Token（全部）',
    'admin.overallTokenSummary': 'Token 使用总览',
    'admin.pastWeek': '过去一周',
    'admin.pastMonth': '过去一月',
    'admin.noTokenStats': '暂无 Token 统计数据',
    'admin.loadStatistics': '加载统计',
    'admin.inShort': '输入',
    'admin.outShort': '输出',
    'admin.dashboardLoadError': '网络错误，加载仪表盘统计失败',
    'admin.tokenStatsLoadError': '加载 Token 统计失败',
    'admin.tokenStatsNetworkError': '网络错误，加载 Token 统计失败',
    'admin.managementInterface': '管理界面',
    'admin.todayRegistrations': '今日注册',
    'admin.topSchoolsByTokens': '学校 Token 使用排行',
    'admin.schoolName': '学校名称',
    'admin.schoolCode': '学校代码',
    'admin.schoolCodeAutoGenerated': '根据学校名称自动生成',
    'admin.regenerateSchoolCode': '重新生成学校代码',
    'admin.invitationCodeAutoGenerated': '邀请码将在创建后自动生成。',
    'admin.schoolNameRequired': '请输入学校名称',
    'admin.schoolCodeRequired': '无法从名称生成代码，请手动输入学校代码。',
    'admin.search': '搜索',
    'admin.reset': '重置',
    'admin.actions': '操作',
    'admin.createSchool': '创建学校',
    'admin.editSchool': '编辑学校',
    'admin.createApiKey': '创建 API 密钥',
    'admin.editApiKey': '编辑 API 密钥',
    'admin.name': '姓名',
    'admin.phone': '手机号',
    'admin.organization': '学校',
    'admin.tokensUsed': 'Token 使用量',
    'admin.registrationTime': '注册时间',
    'admin.status': '状态',
    'admin.usersCount': '用户数',
    'admin.apiKey': 'API 密钥',
    'admin.usage': '使用量',
    'admin.created': '创建时间',
    'admin.lastUsed': '最后使用',
    'admin.enabled': '启用',
    'admin.disabled': '禁用',
    'admin.save': '保存',
    'admin.cancel': '取消',
    'admin.delete': '删除',
    'admin.refresh': '刷新',
    'admin.filterBySchool': '按学校筛选',
    'admin.allSchools': '全部学校',
    'admin.previous': '上一页',
    'admin.next': '下一页',
    'admin.noData': '暂无数据',
    'admin.loading': '加载中...',
    'admin.description': '描述',
    'admin.shareInviteTitle': '分享邀请',
    'admin.copyShareMessage': '复制',
    'admin.shareInviteMessage':
      '尊敬的校领导，您好！诚挚邀请您与学校团队体验 MindGraph —— 我们倾力打造的AI思维图示生成软件，致力于开发思维教学信息化平台。贵校的专属邀请码是：{code} 请您访问 mg.mingspringedu.com 完成注册，开启高效、直观的思维可视化协作。期待能为贵校的教育创新增添一份力量。',
    'admin.trendChart': '趋势图表',
    'admin.trendUsers': '总用户数趋势',
    'admin.trendOrganizations': '学校数量趋势',
    'admin.trendRegistrations': '每日注册趋势',
    'admin.trendTokens': 'Token 使用趋势',
    'admin.trendOrgTokens': '学校 Token 使用趋势',
    'admin.trendUserTokens': '用户 Token 使用趋势',
    'admin.displayNameLabel': '侧边栏显示文字',
    'admin.displayNameHint': '用户侧边栏显示的自定义文字（如 MindGraph专业版）。留空则显示学校名称。',
    'admin.lockOrganization': '锁定学校',
    'admin.unlockOrganization': '解锁学校',
    'admin.deleteOrganization': '删除学校',
    'admin.deleteOrgConfirm': '确定删除学校 {name}？此操作不可撤销。',
    'admin.deleteOrgConfirmWithUsers':
      '确定删除学校 {name} 及其全部 {count} 个用户账号？此操作不可撤销。',
    'admin.dangerZone': '危险操作',
    'admin.expirationDate': '到期日期',
    'admin.expirationDateHint': '超过此日期后学校将被锁定。留空表示无限制。',
    'admin.noExpiration': '无限制',

    // Library admin tab
    'admin.library': '图书馆',
    'admin.library.tabTitle': '图书馆管理',
    'admin.library.tabSubtitle': '扫描、注册和管理图片书籍文件夹',
    'admin.library.scan': '扫描',
    'admin.library.scanning': '正在扫描存储目录...',
    'admin.library.registerAll': '批量注册新书',
    'admin.library.register': '注册',
    'admin.library.reRegister': '重新注册',
    'admin.library.lastScanned': '上次扫描',
    'admin.library.totalFolders': '文件夹总数',
    'admin.library.registered': '已注册',
    'admin.library.visible': '显示中',
    'admin.library.newUnregistered': '未注册',
    'admin.library.colTitle': '书名 / 文件夹',
    'admin.library.colPages': '页数',
    'admin.library.colStatus': '状态',
    'admin.library.colVisible': '显示',
    'admin.library.colActions': '操作',
    'admin.library.statusNew': '未注册',
    'admin.library.statusRegistered': '已注册',
    'admin.library.statusRepair': '路径修复',
    'admin.library.statusOrphaned': '孤立记录',
    'admin.library.diskPresent': '文件夹存在于磁盘',
    'admin.library.diskMissing': '磁盘上未找到文件夹',
    'admin.library.storageDir': '存储路径',
    'admin.library.noFolders': '在 storage/library/ 中未找到图片文件夹',
    'admin.library.scanError': '扫描图书馆存储目录失败',
    'admin.library.registerSuccess': '图书注册成功',
    'admin.library.registerAllSuccess': '已注册',
    'admin.library.registerError': '图书注册失败',
    'admin.library.visibilityError': '更新可见性失败',
    'admin.library.renamePages': '重命名页面',
    'admin.library.renameDialogTitle': '重命名页面文件',
    'admin.library.renameBookNameLabel': '书名前缀',
    'admin.library.renameBookNameHint': '文件将被重命名为',
    'admin.library.renamePreview': '预览',
    'admin.library.renamePreviewLoading': '正在生成重命名方案...',
    'admin.library.renameColFrom': '当前文件名',
    'admin.library.renameColTo': '新文件名',
    'admin.library.renameFilesToRename': '个文件待重命名',
    'admin.library.renameFilesAlreadyOk': '个已正确命名',
    'admin.library.renameNoChanges': '所有文件均已正确命名',
    'admin.library.renameApply': '执行重命名',
    'admin.library.renameSuccess': '成功重命名 {count} 个文件',
    'admin.library.renameError': '重命名失败',
    'admin.library.generateCover': '生成封面',
    'admin.library.generateCoverSuccess': '封面生成成功',
    'admin.library.generateCoverError': '封面生成失败',
    'admin.library.deleteBook': '删除书籍',
    'admin.library.deleteBookTitle': '删除书籍',
    'admin.library.deleteBookConfirmMsg': '永久从磁盘删除 "{name}" 的全部 {count} 张页面图片及数据库记录？此操作不可撤销。',
    'admin.library.deleteBookConfirm': '确认全部删除',
    'admin.library.deleteBookSuccess': '书籍已删除',
    'admin.library.deleteRecord': '删除记录',
    'admin.library.deleteConfirmTitle': '删除文档记录',
    'admin.library.deleteConfirmMsg': '永久删除 "{name}" 的数据库记录？磁盘上的图片文件不受影响。',
    'admin.library.deleteSuccess': '记录已删除',
    'admin.library.deleteError': '删除失败',

    // Workshop Chat
    'workshop.title': '工作坊',
    'workshop.channels': '频道',
    'workshop.dms': '私信',
    'workshop.directMessages': '私信',
    'workshop.conversations': '对话',
    'workshop.generalChat': '综合讨论',
    'workshop.topics': '话题',
    'workshop.recentTopics': '最近话题',
    'workshop.newTopic': '新建话题',
    'workshop.noTopicsYet': '暂无话题',
    'workshop.showAllTopics': '显示全部话题',
    'workshop.more': '更多',
    'workshop.createStudyCaseHint': '创建一个话题开始吧',
    'workshop.noConversationsYet': '暂无话题',
    'workshop.selectConversation': '选择一个对话',
    'workshop.noChannelsJoined': '尚未加入任何频道',
    'workshop.noChannelsAvailable': '暂无可用频道',
    'workshop.noMessagesYet': '暂无消息',
    'workshop.startConversation': '开始对话吧！',
    'workshop.members': '成员',
    'workshop.topicCount': '个话题',
    'workshop.join': '加入',
    'workshop.leave': '离开',
    'workshop.create': '创建',
    'workshop.viewDiagram': '查看图示',
    'workshop.diagram': '图示',
    'workshop.by': '创建者',
    'workshop.unknown': '未知',
    'workshop.edited': '（已编辑）',
    'workshop.messageDeleted': '此消息已被删除',
    'workshop.newMessage': '发送消息...',
    'workshop.typeMessagePlaceholder': '输入消息...（回车发送，Shift+回车换行）',
    'workshop.topicTitle': '标题',
    'workshop.topicTitlePlaceholder': '例如：集体备课讨论、课堂观察',
    'workshop.topicDescription': '描述',
    'workshop.topicDescriptionPlaceholder': '描述话题内容...',
    'workshop.conversationTitle': '话题标题',
    'workshop.conversationTitlePlaceholder': '例如：集体备课讨论、教学反思',
    'workshop.startConversationHint': '创建一个话题，与同事展开讨论',
    'workshop.view': '查看',
    'workshop.dismiss': '关闭',
    'workshop.statusOpen': '进行中',
    'workshop.statusInProgress': '处理中',
    'workshop.statusCompleted': '已完成',
    'workshop.statusArchived': '已归档',
    'workshop.mentionedInChannel': '你在 #{0} 中被提及',
    'workshop.mentionedInTopic': '你在 {0} 中被提及',
    'workshop.directMessage': '私信',
    'workshop.contacts': '通讯录',
    'workshop.startDM': '发消息',
    'workshop.noMembersFound': '未找到成员',
    'workshop.searchMembers': '搜索成员...',
    'workshop.switchSchool': '切换学校',
    'workshop.allSchools': '全部学校',
    'workshop.viewingSchool': '当前查看：{0}',
    'workshop.mySchool': '我的学校',
    'workshop.showMore': '展示更多',
    'workshop.showLess': '收起',
    'workshop.addReaction': '添加表情',
    'workshop.starMessage': '收藏消息',
    'workshop.unstarMessage': '取消收藏',
    'workshop.quoteMessage': '引用消息',
    'workshop.copyLink': '复制链接',
    'workshop.uploadFile': '上传文件',
    'workshop.download': '下载',
    'workshop.linkCopied': '链接已复制',
    'workshop.bold': '粗体',
    'workshop.italic': '斜体',
    'workshop.code': '代码',
    'workshop.codeBlock': '代码块',
    'workshop.strikethrough': '删除线',
    'workshop.insertLink': '插入链接',
    'workshop.emoji': '表情',
    'workshop.moreActions': '更多操作',
    'workshop.searchMessages': '搜索消息...',
    'workshop.newConversation': '新建话题',
    'workshop.selectTopic': '选择话题',
    'workshop.youAnd': '你和',
    'workshop.online': '在线',
    'workshop.offline': '离线',
    'workshop.filterUsers': '筛选用户',
    'workshop.filterSidebar': '筛选频道、私信',
    'workshop.views': '视图',
    'workshop.inbox': '收件箱',
    'workshop.starred': '星标消息',
    'workshop.mentions': '提及我的',
    'workshop.browseChannels': '浏览频道',
    'workshop.newDM': '新建私信',
    'workshop.composeMessage': '撰写消息',
    'workshop.composeMessageTo': '发送消息到',
    'workshop.startNewConversation': '开始新对话',
    'workshop.newDirectMessage': '新建私信',
    'workshop.noMembers': '暂无成员',
    'workshop.thisConversation': '此对话',
    'workshop.thisChannel': '此频道',
    'workshop.others': '其他用户',
    'workshop.viewAllMembers': '查看所有成员',
    'workshop.you': '（你）',
    'workshop.announceChannels': '公告频道',
    'workshop.publicChannels': '公开频道',
    'workshop.privateChannels': '私有频道',
    'workshop.channelSettings': '频道设置',
    'workshop.channelType': '频道类型',
    'workshop.channelTypeAnnounce': '公告',
    'workshop.channelTypePublic': '公开',
    'workshop.channelTypePrivate': '私有',
    'workshop.postingPolicy': '发布权限',
    'workshop.policyEveryone': '所有人',
    'workshop.policyManagers': '仅管理员',
    'workshop.policyMembersOnly': '仅成员',
    'workshop.defaultChannel': '默认频道',
    'workshop.muteChannel': '静音频道',
    'workshop.unmuteChannel': '取消静音',
    'workshop.pinChannel': '置顶频道',
    'workshop.unpinChannel': '取消置顶',
    'workshop.channelColor': '频道颜色',
    'workshop.notifications': '通知',
    'workshop.desktopNotifications': '桌面通知',
    'workshop.emailNotifications': '邮件通知',
    'workshop.topicSettings': '话题设置',
    'workshop.moveTopic': '移动到课例',
    'workshop.renameTopic': '重命名话题',
    'workshop.deleteTopic': '删除话题',
    'workshop.deleteTopicConfirm': '确定要删除此话题吗？',
    'workshop.markAsRead': '标记为已读',
    'workshop.muteTopic': '静音话题',
    'workshop.unmuteTopic': '取消静音话题',
    'workshop.followTopic': '关注话题',
    'workshop.unfollowTopic': '取消关注话题',
    'workshop.permissions': '权限',
    'workshop.gearMenu': '设置',
    'workshop.personalMenu': '个人菜单',
    'workshop.toggleContacts': '通讯录开关',
    'workshop.profile': '个人资料',
    'workshop.preferences': '偏好设置',
    'workshop.signOut': '退出登录',
    'workshop.viewProfile': '查看个人资料',
    'workshop.sendDirectMessage': '发送私信',
    'workshop.replyMentioning': '回复并提及用户',
    'workshop.copyMentionSyntax': '复制提及语法',
    'workshop.manageUser': '管理此用户',
    'workshop.presenceActive': '在线',
    'workshop.presenceIdle': '离开',
    'workshop.presenceOffline': '离线',
    'workshop.roleAdmin': '管理员',
    'workshop.roleManager': '校管理员',
    'workshop.roleOwner': '所有者',

    // Notifications
    'notification.saved': '保存成功',
    'notification.copied': '已复制到剪贴板',
    'notification.copyFailed': '复制失败',
    'notification.deleted': '删除成功',
    'notification.sessionInvalidated': '您已被登出，因为登录设备数量超过上限',
    'notification.newVersionAvailable': '新版本已发布，点击刷新。',
  },
}

/** Dimension label translations (English → Chinese) for brace/tree map classification */
export const DIMENSION_TRANSLATIONS: Record<string, string> = {
  'Physical Characteristics': '物理特征',
  Parts: '组成部分',
  Components: '组件',
  Structure: '结构',
  Attributes: '属性',
  Properties: '属性',
  Types: '类型',
  Kinds: '种类',
  Categories: '类别',
  Characteristics: '特征',
  Features: '特点',
  Elements: '要素',
  Aspects: '方面',
  Factors: '因素',
}

export function translateDimension(value: string, toChinese: boolean): string {
  if (!toChinese || !value?.trim()) return value
  const trimmed = value.trim()
  return DIMENSION_TRANSLATIONS[trimmed] ?? trimmed
}

export function useLanguage() {
  const uiStore = useUIStore()

  const currentLanguage = computed(() => uiStore.language)
  const isZh = computed(() => uiStore.language === 'zh')
  const isEn = computed(() => uiStore.language === 'en')

  function t(key: string, fallback?: string): string {
    const dict = translations[uiStore.language]
    return dict[key] || fallback || key
  }

  function setLanguage(lang: Language): void {
    uiStore.setLanguage(lang)
  }

  function toggleLanguage(): void {
    uiStore.toggleLanguage()
  }

  function getNotification(key: string, ...args: unknown[]): string {
    let message = t(`notification.${key}`)

    // Simple template replacement
    args.forEach((arg, index) => {
      message = message.replace(`{${index}}`, String(arg))
    })

    return message
  }

  return {
    currentLanguage,
    isZh,
    isEn,
    t,
    setLanguage,
    toggleLanguage,
    getNotification,
  }
}
