<script setup lang="ts">
/**
 * CanvasPage - Full canvas editor page with Vue Flow integration
 */
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'

import { AIModelSelector, CanvasToolbar, CanvasTopBar, ZoomControls } from '@/components/canvas'
import DiagramCanvas from '@/components/diagram/DiagramCanvas.vue'
import PromptInput from '@/components/editor/PromptInput.vue'
import { eventBus, useLanguage, useNotifications } from '@/composables'
import { useAuthStore, useDiagramStore, useUIStore } from '@/stores'
import type { DiagramType } from '@/types'
import { authFetch } from '@/utils/api'

const diagramStore = useDiagramStore()
const uiStore = useUIStore()
const _authStore = useAuthStore()
const { isZh } = useLanguage()
const notify = useNotifications()

const isGenerating = ref(false)
const showPromptInput = ref(false)
const hasAutoGenerated = ref(false)
const customPrompt = ref<string | null>(null)

// Map Chinese diagram type names to DiagramType
const diagramTypeMap: Record<string, DiagramType> = {
  圆圈图: 'circle_map',
  气泡图: 'bubble_map',
  双气泡图: 'double_bubble_map',
  树形图: 'tree_map',
  括号图: 'brace_map',
  流程图: 'flow_map',
  复流程图: 'multi_flow_map',
  桥型图: 'bridge_map',
  思维导图: 'mindmap',
  概念图: 'concept_map',
}

// Default prompts for each diagram type
const defaultPrompts: Partial<Record<DiagramType, { zh: string; en: string }>> = {
  circle_map: {
    zh: '创建一个圆圈图，主题是"学习"',
    en: 'Create a circle map about "Learning"',
  },
  bubble_map: {
    zh: '创建一个气泡图，描述"春天"的特征',
    en: 'Create a bubble map describing characteristics of "Spring"',
  },
  double_bubble_map: {
    zh: '创建一个双气泡图，比较"猫"和"狗"',
    en: 'Create a double bubble map comparing "Cats" and "Dogs"',
  },
  tree_map: {
    zh: '创建一个树形图，分类"动物"',
    en: 'Create a tree map categorizing "Animals"',
  },
  brace_map: {
    zh: '创建一个括号图，分解"汽车"的组成部分',
    en: 'Create a brace map decomposing parts of a "Car"',
  },
  flow_map: {
    zh: '创建一个流程图，展示"制作咖啡"的步骤',
    en: 'Create a flow map showing steps to "Make Coffee"',
  },
  multi_flow_map: {
    zh: '创建一个复流程图，分析"下雨"的原因和结果',
    en: 'Create a multi-flow map analyzing causes and effects of "Rain"',
  },
  bridge_map: {
    zh: '创建一个桥型图，展示"首都到国家"的类比关系',
    en: 'Create a bridge map showing analogies of "Capital to Country"',
  },
  mindmap: {
    zh: '创建一个思维导图，主题是"人工智能"',
    en: 'Create a mind map about "Artificial Intelligence"',
  },
  concept_map: {
    zh: '创建一个概念图，展示"生态系统"的概念关系',
    en: 'Create a concept map showing relationships in "Ecosystem"',
  },
}

// Get diagram type from UI store (set before navigation)
const chartType = computed(() => uiStore.selectedChartType)

const diagramType = computed<DiagramType | null>(() => {
  if (!chartType.value) return null
  return diagramTypeMap[chartType.value] || null
})

async function generateDiagram(prompt: string) {
  if (!prompt.trim() || !diagramType.value) return

  isGenerating.value = true
  showPromptInput.value = false

  try {
    const response = await authFetch('/api/generate_graph', {
      method: 'POST',
      body: JSON.stringify({
        prompt: prompt.trim(),
        diagram_type: diagramType.value,
        language: isZh.value ? 'zh' : 'en',
        llm: 'qwen',
      }),
    })

    if (!response.ok) {
      const error = await response.json().catch(() => ({ detail: 'Failed to generate diagram' }))
      throw new Error(error.detail || 'Failed to generate diagram')
    }

    const result = await response.json()

    if (result.success && result.spec) {
      // Use diagram_type from response if available, otherwise use URL param
      const finalDiagramType = (result.diagram_type as DiagramType) || diagramType.value
      if (!finalDiagramType) {
        throw new Error('No diagram type specified')
      }

      // Load the spec into the diagram store
      const loaded = diagramStore.loadFromSpec(result.spec, finalDiagramType)
      if (loaded) {
        notify.success(isZh.value ? '图表生成成功' : 'Diagram generated successfully')
      } else {
        throw new Error('Failed to load diagram data')
      }
    } else {
      throw new Error(result.error || 'Failed to generate diagram')
    }
  } catch (error) {
    console.error('Failed to generate diagram:', error)
    notify.error(
      error instanceof Error ? error.message : isZh.value ? '生成失败' : 'Generation failed'
    )
    showPromptInput.value = true
  } finally {
    isGenerating.value = false
  }
}

function handleZoomChange(_level: number) {
  // Zoom is handled by DiagramCanvas
}

function handleFitToScreen() {
  // Fit view is handled by DiagramCanvas
}

function handleHandToolToggle(_active: boolean) {
  // Hand tool is handled by DiagramCanvas
}

function handleStartPresentation() {
  // TODO: Implement presentation mode
}

function handleModelChange(model: string) {
  // TODO: Handle AI model change
  console.log('Selected model:', model)
}

// Auto-generate diagram when type is provided
async function autoGenerateDiagram() {
  if (!diagramType.value || hasAutoGenerated.value || isGenerating.value) return

  hasAutoGenerated.value = true
  isGenerating.value = true

  // Use custom prompt if provided (from template input), otherwise use default
  const defaultPrompt = diagramType.value ? defaultPrompts[diagramType.value] : undefined
  const prompt =
    customPrompt.value || (defaultPrompt ? defaultPrompt[isZh.value ? 'zh' : 'en'] : '')

  if (!prompt) {
    // No prompt available, show input instead
    showPromptInput.value = true
    isGenerating.value = false
    return
  }

  await generateDiagram(prompt)
}

// Listen for custom prompt from template input
const unsubPrompt = eventBus.onWithOwner(
  'canvas:generate_with_prompt',
  (data) => {
    if (data.prompt) {
      customPrompt.value = data.prompt as string
      // Reset auto-generation flag to allow regeneration
      hasAutoGenerated.value = false
      // Trigger auto-generation with custom prompt
      if (diagramType.value) {
        autoGenerateDiagram()
      }
    }
  },
  'CanvasPage'
)

// Watch for diagram type changes in store
watch(
  () => uiStore.selectedChartType,
  () => {
    // Reset auto-generation flag when type changes
    hasAutoGenerated.value = false

    if (diagramType.value) {
      diagramStore.setDiagramType(diagramType.value)
      // Load default template if we have a type and no existing diagram
      if (!diagramStore.data) {
        // Load static default template (no AI generation)
        diagramStore.loadDefaultTemplate(diagramType.value)
      }
    } else {
      // No type specified, show prompt input
      showPromptInput.value = true
    }
  },
  { immediate: true }
)

onMounted(() => {
  // Initialize diagram type from store
  if (diagramType.value) {
    diagramStore.setDiagramType(diagramType.value)
    // Load default template on mount if type is provided and no existing diagram
    if (!diagramStore.data) {
      // Load static default template (no AI generation)
      diagramStore.loadDefaultTemplate(diagramType.value)
    }
  } else {
    // No type specified, show prompt input
    showPromptInput.value = true
  }
})

onUnmounted(() => {
  unsubPrompt()
  // Clean up state when leaving canvas - matches old JS behavior
  diagramStore.reset()
  uiStore.setSelectedChartType('选择图示')
})
</script>

<template>
  <div class="canvas-page flex flex-col h-screen bg-gray-50">
    <!-- Top navigation bar -->
    <CanvasTopBar />

    <!-- Floating toolbar -->
    <CanvasToolbar />

    <!-- Main canvas area -->
    <div class="flex-1 relative overflow-hidden pt-16">
      <!-- Loading overlay -->
      <div
        v-if="isGenerating"
        class="absolute inset-0 flex items-center justify-center z-10 bg-gray-50/95"
      >
        <div class="text-center">
          <div class="text-lg font-medium text-gray-700 dark:text-gray-300 mb-2">
            {{ isZh ? '正在生成图表...' : 'Generating diagram...' }}
          </div>
          <div class="text-sm text-gray-500 dark:text-gray-400">
            {{ isZh ? '请稍候' : 'Please wait' }}
          </div>
        </div>
      </div>

      <!-- Prompt input overlay (shown when no diagram and not generating) -->
      <div
        v-if="showPromptInput && !diagramStore.data && !isGenerating"
        class="absolute inset-0 flex items-center justify-center z-10 bg-gray-50/95"
      >
        <div class="w-full max-w-2xl px-6">
          <h2 class="text-2xl font-bold text-center mb-6 text-gray-800 dark:text-white">
            {{ isZh ? '创建' + chartType : 'Create ' + chartType }}
          </h2>
          <PromptInput
            :is-loading="isGenerating"
            @submit="generateDiagram"
          />
        </div>
      </div>

      <!-- Vue Flow Canvas -->
      <DiagramCanvas
        v-if="diagramStore.data"
        class="w-full h-full"
        :show-background="true"
        :show-controls="true"
        :show-minimap="false"
        :fit-view-on-init="true"
      />
    </div>

    <!-- Zoom controls (bottom right) -->
    <ZoomControls
      @zoom-change="handleZoomChange"
      @fit-to-screen="handleFitToScreen"
      @hand-tool-toggle="handleHandToolToggle"
      @start-presentation="handleStartPresentation"
    />

    <!-- AI model selector (bottom center) -->
    <AIModelSelector @model-change="handleModelChange" />
  </div>
</template>
