"""
Supported MindGraph UI (interface) locale codes.

Keep in sync with `code` values in frontend/src/i18n/supportedUiLocales.ts (`SUPPORTED_UI_LOCALES`).
"""

UI_LANGUAGE_CODES = frozenset(
    {
        "af",
        "am",
        "ar",
        "az",
        "bg",
        "bn",
        "ca",
        "cs",
        "da",
        "de",
        "el",
        "en",
        "es",
        "fa",
        "fi",
        "fr",
        "ha",
        "he",
        "hi",
        "hr",
        "hu",
        "hy",
        "id",
        "ig",
        "it",
        "ja",
        "ka",
        "kk",
        "km",
        "ko",
        "ky",
        "lo",
        "mn",
        "ms",
        "my",
        "ne",
        "nl",
        "no",
        "pl",
        "pt",
        "ro",
        "ru",
        "si",
        "so",
        "sr",
        "ss",
        "st",
        "sv",
        "sw",
        "ta",
        "tg",
        "th",
        "tk",
        "tl",
        "tn",
        "tr",
        "ug",
        "uk",
        "ur",
        "uz",
        "vi",
        "xh",
        "yo",
        "zh",
        "zh-tw",
        "zu",
    }
)


def is_ui_language(value: str) -> bool:
    """Return True if value is a supported interface locale code."""
    return value in UI_LANGUAGE_CODES
