/**
 * Rotating one-sentence chat copy pools (welcome / generate / done).
 */
export type OneSentenceChatLocale = "zh" | "zh-tw" | "en"

export const WELCOME_ZH = [
"你好，告诉我你想画什么思维图示，或之后继续让我帮你修改。",
"嗨，我是 Kitty。用一句话描述主题，我来帮你生成导图。",
"准备好了。直接说想画什么，或让我改分支、补节点。",
"从一句想法开始吧——主题、分支、补全，都可以跟我说。",
"想画什么？丢给我一个主题，我们一起搭出结构。",
"我在这儿。说个主题，或直接让我改现有导图。",
"一句话就够：主题、几个分支，或「帮我补全」。",
"今天想梳理什么？告诉我，我来画成导图。",
"有想法就说——新建、改主题、加分支，我都能接。",
"先说主题，还是先改某一支？我听你的。",
"把脑子里的那句话发过来，我帮你落成图。",
"随时可以开始：描述一下你想看的结构。",
"我是 Kitty，擅长把一句话变成清晰的思维导图。",
"不用客气，直接说「加一条分支」或「改主题」就行。",
"导图还没开？说个主题；已经有了？说怎么改。",
"想快速出图的话，给我主题和大概分支数就好。",
"聊聊你的主题吧，我来帮你理出层次。",
"改节点、补内容、换主题——一句指令即可。",
"准备画图了吗？把需求用自然语言发给我。",
"我可以生成，也可以边聊边改，你选。",
"说「自动补全」我会填细节；说主题我会先搭骨架。",
"有个模糊想法也没关系，我们一步步细化。",
"你好呀。想从中心主题开始，还是先加几条主分支？",
"把要整理的内容告诉我，我帮你排成导图。",
"我在听。主题、分类方式、层级深度都可以提。",
"一句话生成，或继续编辑——两种模式我都熟。",
"需要灵感？先丢个关键词，我帮你展开。",
"改字、加枝、删枝、补全，都可以用口语跟我说。",
"今天的导图想讲什么故事？从主题说起吧。",
"别担心措辞，听懂大意我就动手。",
"想要简洁版还是详细版？生成时跟我说一声。",
"我在画布旁待命，发指令即可。",
"新建一张，还是在现有图上微调？告诉我。",
"主题定了吗？定了就说出来，我帮你铺开。",
"像聊天一样说需求就行，不必记命令格式。",
"嗨～准备好把想法画出来了吗？",
"你可以先生成骨架，再让我逐支补全。",
"节点名字不满意？直接说改成什么。",
"分支太少或太多都能调，跟我说目标结构。",
"我擅长中文主题的导图，英文也可以。",
"来吧，一句描述，一张图。",
"有现成大纲的话，贴过来，我帮你结构化。",
"想对比、流程还是发散？说类型或直接说内容。",
"我可以边生成边按你的反馈调整。",
"先画中心，再长分支——你也可以一次说完。",
"需要课堂用、会议用还是自学用？用途也能提。",
"说「补完这张图」，我会尽量填满合理内容。",
"欢迎回来。继续改这张，或换个新主题都行。",
"有问题就问，有修改就说，我跟着你的节奏。",
"准备好了就发第一条消息吧，我马上开工。",
"把复杂主题拆开讲也行，我帮你收成一张图。",
"你好！今天想让导图帮你记住什么、讲清什么？",
] as const

export const WELCOME_ZH_TW = [
"你好，告訴我你想畫什麼思維圖示，或之後繼續讓我幫你修改。",
"嗨，我是 Kitty。用一句話描述主題，我來幫你生成導圖。",
"準備好了。直接說想畫什麼，或讓我改分支、補節點。",
"從一句想法開始吧——主題、分支、補全，都可以跟我說。",
"想畫什麼？丟給我一個主題，我們一起搭出結構。",
"我在這兒。說個主題，或直接讓我改現有導圖。",
"一句話就夠：主題、幾個分支，或「幫我補全」。",
"今天想梳理什麼？告訴我，我來畫成導圖。",
"有想法就說——新建、改主題、加分支，我都能接。",
"先說主題，還是先改某一支？我聽你的。",
"把腦子裡的那句話發過來，我幫你落成圖。",
"隨時可以開始：描述一下你想看的結構。",
"我是 Kitty，擅長把一句話變成清晰的思維導圖。",
"不用客氣，直接說「加一條分支」或「改主題」就行。",
"導圖還沒開？說個主題；已經有了？說怎麼改。",
"想快速出圖的話，給我主題和大概分支數就好。",
"聊聊你的主題吧，我來幫你理出層次。",
"改節點、補內容、換主題——一句指令即可。",
"準備畫圖了嗎？把需求用自然語言發給我。",
"我可以生成，也可以邊聊邊改，你選。",
"說「自動補全」我會填細節；說主題我會先搭骨架。",
"有個模糊想法也沒關係，我們一步步細化。",
"你好呀。想從中心主題開始，還是先加幾條主分支？",
"把要整理的內容告訴我，我幫你排成導圖。",
"我在聽。主題、分類方式、層級深度都可以提。",
"一句話生成，或繼續編輯——兩種模式我都熟。",
"需要靈感？先丟個關鍵詞，我幫你展開。",
"改字、加枝、刪枝、補全，都可以用口語跟我說。",
"今天的導圖想講什麼故事？從主題說起吧。",
"別擔心措辭，聽懂大意我就動手。",
"想要簡潔版還是詳細版？生成時跟我說一聲。",
"我在畫布旁待命，發指令即可。",
"新建一張，還是在現有圖上微調？告訴我。",
"主題定了嗎？定了就說出來，我幫你鋪開。",
"像聊天一樣說需求就行，不必記命令格式。",
"嗨～準備好把想法畫出來了嗎？",
"你可以先生成骨架，再讓我逐支補全。",
"節點名字不滿意？直接說改成什麼。",
"分支太少或太多都能調，跟我說目標結構。",
"我擅長中文主題的導圖，英文也可以。",
"來吧，一句描述，一張圖。",
"有現成大綱的話，貼過來，我幫你結構化。",
"想對比、流程還是發散？說類型或直接說內容。",
"我可以邊生成邊按你的回饋調整。",
"先畫中心，再長分支——你也可以一次說完。",
"需要課堂用、會議用還是自學用？用途也能提。",
"說「補完這張圖」，我會盡量填滿合理內容。",
"歡迎回來。繼續改這張，或換個新主題都行。",
"有問題就問，有修改就說，我跟著你的節奏。",
"準備好了就發第一條訊息吧，我馬上開工。",
"把複雜主題拆開講也行，我幫你收成一張圖。",
"你好！今天想讓導圖幫你記住什麼、講清什麼？",
] as const

export const WELCOME_EN = [
"Hi — tell me what diagram to create, or keep chatting to edit branches and nodes.",
"Hi, I'm Kitty. Describe a topic in one sentence and I'll build the map.",
"Ready when you are — say what to draw, or ask me to edit branches and nodes.",
"Start with one idea — topic, branches, or fill-in — just tell me.",
"What should we map? Drop a topic and I'll sketch the structure.",
"I'm here. Give me a theme, or tell me how to tweak the current map.",
"One sentence is enough: a topic, a few branches, or “auto-complete this.”",
"What are we organizing today? Tell me and I'll turn it into a mind map.",
"Share an idea — new map, rename the topic, add a branch — I've got it.",
"Topic first, or edit a branch first? Your call.",
"Send the thought in your head; I'll land it on the canvas.",
"Whenever you're ready: describe the structure you want to see.",
"I'm Kitty — I turn plain language into a clear mind map.",
"No special syntax: say “add a branch” or “change the topic.”",
"No map yet? Give a topic. Already have one? Tell me what to change.",
"For a quick draft, topic plus rough branch count works great.",
"Talk through your theme; I'll help layer it out.",
"Rename, fill, swap the center — one instruction is enough.",
"Ready to draw? Send the request in natural language.",
"I can generate from scratch or edit as we chat — you choose.",
"Say “auto-complete” for detail, or give a topic for the skeleton.",
"Vague ideas are fine — we'll refine step by step.",
"Hi. Start from the center topic, or add a few main branches first?",
"Tell me what you're sorting out; I'll arrange it as a map.",
"Listening — topic, categories, and depth are all fair game.",
"One-shot generate or keep editing — both modes are fine.",
"Need a spark? Toss a keyword and I'll expand it.",
"Rename, add, delete, complete — everyday language works.",
"What story should today's map tell? Start with the topic.",
"Don't overthink wording — if I get the gist, I'll act.",
"Want lean or detailed? Mention it when we generate.",
"Standing by the canvas — send a command anytime.",
"New diagram, or a small tweak on this one? Tell me.",
"Got a topic? Say it and I'll spread it out.",
"Chat normally; you don't need to memorize commands.",
"Hey — ready to get that idea onto a map?",
"We can build a skeleton first, then fill branch by branch.",
"Don't like a label? Just say what it should become.",
"Too few or too many branches? Describe the shape you want.",
"Chinese or English topics both work for me.",
"One description, one map — let's go.",
"Have an outline already? Paste it and I'll structure it.",
"Compare, process, or brainstorm? Name the type or just the content.",
"I can generate, then adjust from your feedback.",
"Center first then branches — or say it all at once.",
"Class, meeting, or study notes? Purpose helps if you mention it.",
"Say “finish this map” and I'll fill in sensible content.",
"Welcome back. Keep editing this one, or start a new topic.",
"Ask questions or request edits — I'll follow your pace.",
"Send the first message when you're ready and I'll start.",
"Break a complex theme into pieces; I'll gather it into one map.",
"Hi! What should this map help you remember or explain today?",
] as const

export const GENERATE_DONE_ZH = [
"导图已生成。继续输入即可修改分支或节点。",
"好了，导图画出来了。想改主题、加分支或自动补全，直接说。",
"生成完成。下一步可以改节点文字，或让我补全整张图。",
"导图就绪。继续聊，我帮你微调结构和内容。",
"画好了。哪里要改，随时说。",
"骨架已经在画布上了，要加细节吗？",
"完成～可以改主题，也可以让我补某一支。",
"图出来了。不满意的节点名直接让我改。",
"生成成功。说「自动补全」我会继续填。",
"好了！继续描述你想要的调整就行。",
"导图已就位。加分支、删分支、改字都可以。",
"先到这里。你一说，我再改。",
"内容已铺开。想更细或更简，告诉我。",
"搞定。接下来想从哪一支动手？",
"已生成。保持聊天，我会跟着改图。",
"看一下中心和主分支，需要的话我马上改。",
"图好了。也可以让我按你的用途再整理一版。",
"生成完毕——随时丢下一条修改指令。",
"可以开始编辑了。口语说需求即可。",
"导图画完了。补全、重命名、换结构都行。",
"完成啦。想换个主题或加地区分支，直接说。",
"已落到画布。继续输入，我继续改。",
] as const

export const GENERATE_DONE_ZH_TW = [
"導圖已生成。繼續輸入即可修改分支或節點。",
"好了，導圖畫出來了。想改主題、加分支或自動補全，直接說。",
"生成完成。下一步可以改節點文字，或讓我補全整張圖。",
"導圖就緒。繼續聊，我幫你微調結構和內容。",
"畫好了。哪裡要改，隨時說。",
"骨架已經在畫布上了，要加細節嗎？",
"完成～可以改主題，也可以讓我補某一支。",
"圖出來了。不滿意的節點名直接讓我改。",
"生成成功。說「自動補全」我會繼續填。",
"好了！繼續描述你想要的調整就行。",
"導圖已就位。加分支、刪分支、改字都可以。",
"先到這裡。你一說，我再改。",
"內容已鋪開。想更細或更簡，告訴我。",
"搞定。接下來想從哪一支動手？",
"已生成。保持聊天，我會跟著改圖。",
"看一下中心和主分支，需要的話我馬上改。",
"圖好了。也可以讓我按你的用途再整理一版。",
"生成完畢——隨時丟下一條修改指令。",
"可以開始編輯了。口語說需求即可。",
"導圖畫完了。補全、重新命名、換結構都行。",
"完成啦。想換個主題或加地區分支，直接說。",
"已落到畫布。繼續輸入，我繼續改。",
] as const

export const GENERATE_DONE_EN = [
"Diagram ready. Keep typing to edit branches or nodes.",
"Done — the map is up. Change the topic, add a branch, or ask me to auto-complete.",
"Generated. Next you can rename nodes or ask me to fill the whole map.",
"Map ready. Keep chatting and I'll refine the structure and content.",
"It's on the canvas. Tell me what to tweak anytime.",
"Skeleton's there — want more detail?",
"All set. Rename the topic or ask me to fill a branch.",
"Here it is. If a label feels off, just say the new wording.",
"Generated. Say “auto-complete” and I'll keep filling.",
"Done! Describe the next adjustment whenever you like.",
"Map in place. Add, remove, or rename — your call.",
"That's the first pass. You speak, I edit.",
"Laid out. Want denser or leaner? Tell me.",
"Ready. Which branch should we touch next?",
"Generated. Keep the chat going and I'll keep editing.",
"Check the center and main branches — I can change them now.",
"Map's up. I can reshape it for class, meeting, or notes.",
"Finished generating — drop the next edit instruction anytime.",
"You can edit now. Everyday language is fine.",
"Map complete. Fill, rename, or restructure — just say it.",
"Done. New topic or a regional branch? Tell me.",
"On the canvas. Keep typing and I'll keep updating.",
] as const

export const GENERATING_ZH = [
"好的，正在生成导图…",
"收到，马上开始画…",
"明白了，我来生成这张图…",
"好，正在把你的想法落成导图…",
"开始生成，稍等片刻…",
"正在搭建结构…",
"我来画，请稍候…",
"好的，生成中…",
"正在整理主题和分支…",
"马上出图…",
"收到主题，开始铺开…",
"正在生成，完成后可继续改…",
"好，我先画出骨架…",
"处理中，导图马上好…",
"正在根据你的描述作图…",
] as const

export const GENERATING_ZH_TW = [
"好的，正在生成導圖…",
"收到，馬上開始畫…",
"明白了，我來生成這張圖…",
"好，正在把你的想法落成導圖…",
"開始生成，稍等片刻…",
"正在搭建結構…",
"我來畫，請稍候…",
"好的，生成中…",
"正在整理主題和分支…",
"馬上出圖…",
"收到主題，開始鋪開…",
"正在生成，完成後可繼續改…",
"好，我先畫出骨架…",
"處理中，導圖馬上好…",
"正在根據你的描述作圖…",
] as const

export const GENERATING_EN = [
"Got it — generating your diagram…",
"On it — drawing the map now…",
"Understood — building the diagram…",
"OK — turning that into a mind map…",
"Starting generation — one moment…",
"Laying out the structure…",
"Drawing now — hang tight…",
"Generating…",
"Organizing the topic and branches…",
"Map coming right up…",
"Topic received — spreading it out…",
"Generating — you can edit after this…",
"OK — sketching the skeleton first…",
"Working on it — almost there…",
"Building from your description…",
] as const


const WELCOME: Record<OneSentenceChatLocale, readonly string[]> = {
  zh: WELCOME_ZH,
  "zh-tw": WELCOME_ZH_TW,
  en: WELCOME_EN,
}

const GENERATE_DONE: Record<OneSentenceChatLocale, readonly string[]> = {
  zh: GENERATE_DONE_ZH,
  "zh-tw": GENERATE_DONE_ZH_TW,
  en: GENERATE_DONE_EN,
}

const GENERATING: Record<OneSentenceChatLocale, readonly string[]> = {
  zh: GENERATING_ZH,
  "zh-tw": GENERATING_ZH_TW,
  en: GENERATING_EN,
}

export function resolveOneSentenceChatLocale(language: string): OneSentenceChatLocale {
  const code = String(language || "").trim().toLowerCase()
  if (code === "zh-tw" || code === "zh-hant" || code.startsWith("zh-hant")) {
    return "zh-tw"
  }
  if (code === "zh" || code.startsWith("zh")) {
    return "zh"
  }
  return "en"
}

export function poolWelcome(locale: OneSentenceChatLocale): readonly string[] {
  return WELCOME[locale]
}

export function poolGenerateDone(locale: OneSentenceChatLocale): readonly string[] {
  return GENERATE_DONE[locale]
}

export function poolGenerating(locale: OneSentenceChatLocale): readonly string[] {
  return GENERATING[locale]
}
