from typing import Any

class DownloadError(Exception): ...

class utils:
    DownloadError: type[DownloadError]

class YoutubeDL:
    def __init__(self, params: dict[str, Any] | None = ...) -> None: ...
    def __enter__(self) -> YoutubeDL: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...
    def extract_info(self, url: str, download: bool = ...) -> dict[str, Any] | None: ...
